### ISSUE TITLE
Bypass EarnAPP security detections

### ISSUE THREAD

**Issue by SkullFace141** [engageub/InternetIncome#102]
Notifications

ETHICAL USE

In line with our commitment to enforce ethical usage of our app we are implementing further changes to enhance the functionality of our network for the benefit of our genuine users.

As of today, the use of VMs, Proxies, and VPNs is prohibited.

For more detailed information, please refer to the following FAQ articles:
[Can I install EarnApp on a Virtual Machine (VM)?](https://help.earnapp.com/hc/en-us/articles/10199416541969-Can-I-install-EarnApp-on-a-virtual-machine-VM)
[Can I use Proxies or a VPN?](https://help.earnapp.com/hc/en-us/articles/10199339150609-Can-I-use-Proxies-or-VPN)
[Can I create multiple accounts?](https://help.earnapp.com/hc/en-us/articles/22066103746961-Can-i-create-multiple-accounts)

These adjustments are designed to ensure the smooth operation of our network, ultimately benefiting all our organic users. We aim to exclusively utilize Dynamic Residential IPs, typically provided by users` home Internet service providers or mobile data, with exception to users that may have a Static home IP which our system will be able to distinguish from a Proxy or VPN.

Last but not least we encourage you to review the "Restrictions" section of our terms of service (TOS) for further details: [EULA](https://earnapp.com/user-agreement)

**Comment by engageub** [comment]
Hello,
This script does not bypass any detections. It only redirects the traffic through network if required.
Proxies or VPNS here may be referred to datacenter or public proxies. It is mentioned about low quality score of IPs.
Where the data goes outside the network is controlled by the script. IP detections are done by earnapp and then payments are made. This script is not responsible for IP detections. 
The script is an integration of multiple docker images and redirects it through specified network when specified.
Its upto you to use it or not. Only IP detections and OS/RAM detections are possible through applications. Docker already creates isolated containers. 

Thank you

**Comment by engageub** [comment]
I am closing this script with respect to the statement from earnapp.
```
"We aim to exclusively utilize Dynamic Residential IPs, typically provided by users` home Internet service providers or mobile data, with exception to users that may have a Static home IP which our system will be able to distinguish from a Proxy or VPN."
```
