### ISSUE TITLE
hektcapcha broken

### ISSUE THREAD

**Issue by copystring** [engageub/InternetIncome#106]
Hi,

I'm on the test branch and using ebesucher, but also adnade. With ebesucher, the hektcapcha in firefox does not work reliable anymore. 9/10 it does not solve the captcha.
I tried https://chromewebstore.google.com/detail/captcha-l%C3%B6ser-auto-hcaptc/hlifkpholllijblknnmbfagnkjneagid?hl=de in chrome and this works very good. hektCaptcha seems broken.
Can we try to get ebesucher in chrome so we can use this better captcha solver? I did not find a good captcha solver for firefox.

**Comment by engageub** [comment]
Hello,

Could you please let me know since when this started happening. 
The captcha is solved till the images are visible to the extension. 
May be the existing models are working and new models are not being downloaded. 
Do you see automated queries? 
The extension may not work in chrome if you are using DNS over HTTPS.
Captcha solving is dependent on the extension and the IP address. I do not own the extension.
However, alternative extensions can be considered if they are more reliable. 
Until we get a different solver for firefox, this cannot be replaced in firefox. 

Custom Firefox and Custom Chrome has been added to test branch. It has not been tested yet. 
It will not restart automatically like ebesucher and adnade. 
You will have to manually install the extensions as you get a new installation of the browser in those containers. 

Thank you

**Comment by copystring** [comment]
> Hello,
> 
> Could you please let me know since when this started happening.

Not exactly sure, but it has been like this for about 2 months. I did not have the time to take a look at this until now.

> Do you see automated queries?

Sometimes. 9/10 the images show up but are not clicked.

> Custom Firefox and Custom Chrome has been added to test branch. It has not been tested yet. It will not restart automatically like ebesucher and adnade. You will have to manually install the extensions as you get a new installation of the browser in those containers.

Thank you. I will try the new custom Chrome feature.

**Comment by copystring** [comment]
I tried to set up custom chrome, but it does not work: 
![image](https://github.com/engageub/InternetIncome/assets/1298861/17faa0d0-6e19-4da4-987f-d6e1c5a619e8)

**Comment by engageub** [comment]
Let me login to my host and have a look at that. As mentioned earlier it was not tested but if there are any errors it will show up.

Thank you

**Comment by engageub** [comment]
Ports are now opened for custom firefox and custom chrome in test branch and are accessible now.

Regarding hektcapcha ,  I see that the captcha is not working when I opened it for another url, however I see earnings for adnade. May be the IP is good that it works only with click or I get 4 image captchas on surfbar or captcha is not being shown. 
However having a working solver is better. For chrome this can be replaced with new captcha solver.

**Comment by engageub** [comment]
Regarding hektcaptcha, there is already an issue opened. The endpoints are not reachable for the models to be downloaded. 

https://github.com/Wikidepia/hektCaptcha-model/issues/2

Thank you

**Comment by copystring** [comment]
Just so I understand, custom chrome/firefox have nothing to do with ebesucher and adnade. I can put in whatever I want and this is saved?

**Comment by engageub** [comment]
> Just so I understand, custom chrome/firefox have nothing to do with ebesucher and adnade. I can put in whatever I want and this is saved?

Yes, you can install whatever extensions you wish and they are just fresh installation of regular browsers. They don't get deleted unless you do so. 

Thank you

**Comment by copystring** [comment]
I noticed some issues.
- If adnade is enabled with custom chrome, 127.0.0.1:700X will show adnade instead of custom chrome
- bash internetincome.sh --delete removes everthing I have set up in custom chrome/firefox

**Comment by engageub** [comment]
1. As mentioned in previous issues chrome ports are hardcoded inside the docker image and two chrome containers should not be used in the same tun2socks network. You will have to run in separate scripts if you wish you use same proxy for two chrome containers. However, this is not an issue with firefox.

2. Yes, for custom containers it deletes all the data if you run with --delete command. You can stop the containers and start if you wish to retain the data instead of deleting it.

**Comment by copystring** [comment]
> 1. As mentioned in previous issues, chrome ports are hardcoded inside the docker image and two chrome containers should not be used in the same tun2socks network. You will have to run in separate scripts if you wish you use same proxy for two chrome containers. However, this is not an issue with firefox.

No Problem. This is OK and I can work with that.


> 2. Yes, for custom containers it deletes all the data if you run with --delete command. You can stop the containers and start if you wish to retain the data instead of deleting it.

OK but when the script is updated I need to delete first before using the new version of the script?

**Comment by engageub** [comment]
If you run custom containers in  a separate folder, you can continue using it irrespective of updates as you need not worry about updating the script as they are just browsers.
However, having an option to retain the data is a plus if you wish to update the same script for the newer versions of browser. It will be added soon after some tests. 

Thank you

**Comment by engageub** [comment]
Code for custom firefox and custom chrome has been deployed with backup folders in test branch. You will have to use --deleteBackup to delete the folders.

Thank you

**Comment by copystring** [comment]
This is nice. I migrated the chrome data from each volume to the data folders after updating the script. After re-running the script, the permissions got set correctly to continue using the chrome profile in custom-chrome-data.
Thank you for this update. Working great.

**Comment by copystring** [comment]
Seems like ebesucher with chrome in docker does not work anymore. Always 0 points.

**Comment by engageub** [comment]
Hi,
I tried using the Adnade surfbar on residential and hosting. Currently, no captcha is being asked. It seems they have removed it. However, for Ebesucher on VPS, a captcha is being asked, while on residential IP, no captcha was asked for the surfbar and I see earnings too. If the captcha is being asked, it is most likely considered as Hosting IP.

The following extension will be added to Chrome for Ebesucher.
https://chromewebstore.google.com/detail/rektcaptcha-recaptcha-sol/bbdhfoclddncoaomddgkaaphcnddbpdh

Thank you

**Comment by copystring** [comment]
OK. Seems like my proxies are the problem. Not sure which proxies work well with ebesucher.

**Comment by engageub** [comment]
Yeah, I guess its the proxies. However, extension in test branch for chrome browser has been updated.

**Comment by copystring** [comment]
Did you manage to get eBesucher running with direct connection? For me, this only works with Firefox.

**Comment by engageub** [comment]
> Did you manage to get eBesucher running with direct connection? For me, this only works with Firefox.

Could you please let me know if the browser is accessible and you see rektcaptcha instead of hektcaptcha?
If you see hektcaptcha, it means you are still using older version.
Also did you set EBESUCHER_USE_CHROME=true in properties file.

Thank you

**Comment by copystring** [comment]
Yes, rektCaptcha works fine. But ebesucher always shows 0 points with chrome. Same setup with Firefox instantly works

**Comment by engageub** [comment]
> Yes, rektCaptcha works fine. But ebesucher always shows 0 points with chrome. Same setup with Firefox instantly works

Thank you for the confirmation. The script is working as expected. Points are given by ebesucher based on browser and IP address or display resolution. If it shows any error message, then it can be modified accordingly. 
Firefox has option to set random display resolution unlike chrome.

Thank you

**Comment by copystring** [comment]
Yes, I'm sure it is the display resolution.

**Comment by copystring** [comment]
I think eBesucher with proxies is dead. Without proxies, I can make eBesucher work in Firefox. I have 20 different proxies from Germany. None of them work with eBesucher in Firefox. Direct connection in Firefox works. Direct connection in Chrome does not work.
But in Firefox captcha solving does not work because of hektCaptcha

**Comment by engageub** [comment]
Hello,
Do you mean direct connection from a different location?
You may custom firefox with the following extension installed. It will only work with residential proxies.
However, this will be added to test branch soon for firefox if hektcaptcha does not add rektcaptcha in firefox addons.

https://addons.mozilla.org/en-US/firefox/addon/noptcha/

Thank you

**Comment by engageub** [comment]
Chrome is used by default in main branch instead of firefox for ebesucher. 
nopecha is considering residential IP as hosting IP for the proxies used. So it has not been installed in firefox as of now. 
It will be installed in firefox whenever a free solver is available. 
There are multiple free audio solvers but they may end up in Automated queries. 
Closing this as main branch has also been updated for ebesucher.

Thank you
