### ISSUE TITLE
Meson not starting

### ISSUE THREAD

**Issue by copystring** [engageub/InternetIncome#107]
Hi,

can you help me with this error? Meson is not starting, and I'm not sure why.

```
...
BitPing Node is not enabled. Ignoring BitPing..
Using default tag: latest
latest: Pulling from jepbura/meson
Digest: sha256:b8a03fd80e010974bd0f7176ef25268f854dc91e9a0006b7af68199109159156
Status: Image is up to date for jepbura/meson:latest
docker.io/jepbura/meson:latest
Starting Meson container..
docker: Error response from daemon: conflicting options: port publishing and the container type network mode.
See 'docker run --help'.
Failed to start container for Meson..Exiting..
```

`netstat -a | grep 9000` as `root` shows no result. It must be something else.

**Comment by engageub** [comment]
For meson node you should not use proxy. Use direct connection with port
open on vps to be publicly accessible.

Thank you

**Comment by copystring** [comment]
Is it the same for mystic?

**Comment by engageub** [comment]
Could you please let me know if you are referring to
mysterium ? If so yes. But you can use vpn or multi IP for mysterium nodes.
Thank you

**Comment by copystring** [comment]
Yes, mysterium. This means when I have proxies, I have to use different properties.conf for mysterium and meson?

**Comment by engageub** [comment]
Yes, for now mysterium and meson do not support proxies. There is already
an open issue for mysterium in FAQ section.
You have to run them in different folder.

**Comment by copystring** [comment]
OK. Thank you!
