### ISSUE TITLE
how many proxies can I use?

### ISSUE THREAD

**Issue by Human4ik1** [engageub/InternetIncome#119]
in a similar repository that also uses docker to run multiple copies of these programs, I ran into a problem: running a maximum of 29 containers.
I wanted to count on at least 1000 copies, but he couldn't even handle 100.
have you checked if you have the same limitation?

**Comment by engageub** [comment]
Hello,
If you have enough CPU and memory and good network speed, you can run more than 1000 proxies.
For advanced users, test branch was created.
If you have more than 1000 proxies, please set the value USE_CUSTOM_NETWORK to true in properties.conf file.

https://github.com/engageub/InternetIncome/tree/test



Thank you

**Comment by engageub** [comment]
Closing this as the answer is given. The script was already tested with more than 1000 proxies.
