### ISSUE TITLE
ip format

### ISSUE THREAD

**Issue by MuoiTom** [engageub/InternetIncome#136]
I wonder if the localhost ip form socks5://127.0.0.1 can be used

**Comment by engageub** [comment]
Hello,
Proxies have to be in the format mentioned in [ReadMe](https://github.com/engageub/InternetIncome?tab=readme-ov-file#proxy-list-example-format).
You can try using localhost IP, but why do you need it, if you are already on the same host.
If there are any issues, you will find it in tun2socks logs.

Thank you
