### ISSUE TITLE
Bitping. "You are not logged in!"

### ISSUE THREAD

**Issue by drdre-lab** [engageub/InternetIncome#153]
Please check the Bitping. I have an error "You are not logged in!" when trying to log in. In test branch. Also, here is a mistake in .bitpingd
![image](https://github.com/user-attachments/assets/4f7c4cab-2853-4d8c-bf7b-b0f4f0c95132)

**Comment by engageub** [comment]
Hello,

It looks like you entered wrong username or password or there is a problem with connection or their server. Please note that official docker image is being used. If there is any issue with their server, we will have to contact the owner of the docker image. 
Are you using ARM64 or AMD64 architecture?
If you already entered wrong data in properties file, please use `--deleteBackup` argument to delete the stored data and then start it.
If your password contains special characters, please place the password in single quotes in `properties.conf` file.

You can try this in the following server. Its working fine. 

Free Server Link: https://labs.play-with-docker.com/ 



Thank you
