### ISSUE TITLE
[Feature request] Traffmonetizer device name not showingon the dashboard

### ISSUE THREAD

**Issue by SkullFace141** [engageub/InternetIncome#16]
[Bug] Traffmonetizer device name not showingon the dashboard

all devices are missing the name

**Comment by engageub** [comment]
Could you please see if you placed the token between quotes "" in properties.conf file.

Thank you

**Comment by SkullFace141** [comment]
its between quotes and earning

**Comment by SkullFace141** [comment]
but no names on the dashboard

**Comment by engageub** [comment]
Its not a bug. Its optional parameter from the documentation. Please see below.

https://hub.docker.com/r/traffmonetizer/cli

Thank you

**Comment by engageub** [comment]
If you wish to add it now, please change line 312 in internetincome.sh file before the changes are pushed to main branch next time.

```
 if CONTAINER_ID=$(sudo  docker run -d --platform=linux/amd64 --restart=always $LOGS_PARAM $NETWORK_TUN $traffmonetizer_volume traffmonetizer/cli start accept --token $TRAFFMONETIZER_TOKEN --device-name $DEVICE_NAME$i); then
```

https://github.com/engageub/InternetIncome/blob/main/internetIncome.sh#L312

Thank you

**Comment by engageub** [comment]
Changes have been pushed to test branch. 

https://github.com/engageub/InternetIncome/tree/test

Thank you
