### ISSUE TITLE
Grass not connect

### ISSUE THREAD

**Issue by hoainv1807** [engageub/InternetIncome#168]
IP not showing in Grass dashboard

log:
rm: cannot remove '/tmp/.X1-lock': No such file or directory
rm: cannot remove '/tmp/.X11-unix': No such file or directory
VNC_PASSWORD environment variable is not set. Using a random password. You
will not be able to access the VNC server.
xauth:  file /home/grass/.Xauthority does not exist
Desktop 'TurboVNC: 5517f9613e23:1 ()' started on display 5517f9613e23:1
Starting applications specified in /opt/TurboVNC/bin/xstartup.turbovnc
Log file is /home/grass/.vnc/5517f9613e23:1.log
MESA: error: ZINK: vkCreateInstance failed (VK_ERROR_INCOMPATIBLE_DRIVER)
glx: failed to create drisw screen
(grass:34): dbind-WARNING **: 22:42:50.070: AT-SPI: Error retrieving accessibility
bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
MESA: error: ZINK: vkCreateInstance failed (VK_ERROR_INCOMPATIBLE_DRIVER)
libEGL warning: egl: failed to create dri2 screen
(grass:34): libayatana-appindicator-WARNING **: 22:42:50.657: Unable to get the session bus: Failed to close file descriptor for child process (Operation not permitted)
(grass:34): LIBDBUSMENU-GLIB-WARNING **: 22:42:50.668: Unable to get session bus: Failed to close file descriptor for child process (Operation not permitted)
/usr/bin/grass
[2024-11-10][22:48:52][grass::utils][ERROR] [WebsocketClient]: unable to read message: WebSocket protocol error: Connection reset without closing handshake
[2024-11-10][22:49:20][grass::utils][ERROR] [WebsocketManager][liveness]: reconnect due to error in pings Trying to work with closed connection
[2024-11-10][22:49:30][grass::utils][ERROR] [WebsocketManager]: unable to connect to wss://proxy2.wynd.network:4444/: Websocket client timeout

**Comment by hoainv1807** [comment]
update: I'm change your docker image to mrcolorrain/grass and it's work perfect. hope you you check if it valid to integrate with your repo

**Comment by hoainv1807** [comment]
> Hello, The logs mention that the application is unable to connect to grass server. Are you using proxy or direct connection? If you are using proxy, are using socks5 proxy? Did you enable socks5 DNS in properties file? If so, please leave the default value as it is for socks5 DNS and try again.
> 
> Thank you

I'm using http resident proxy, it's work with all other app

**Comment by engageub** [comment]
Hello,
This is a Linux Desktop Application which earns 2X the regular chrome extension. 
The docker image mentioned by you uses chrome extension.  We were using similar grass extension earlier but recently changed the docker image which uses linux desktop application and pays 2 times more than the chrome extension. 
I noticed that the latest desktop version is causing this issue. However, it connected after a minute.

The following are the common errors or warnings in grass application at the beginning.

```
rm: cannot remove '/tmp/.X1-lock': No such file or directory
rm: cannot remove '/tmp/.X11-unix': No such file or directory
xauth:  file /home/grass/.Xauthority does not exist

Desktop 'TurboVNC: 1e0956581827:1 ()' started on display 1e0956581827:1

Starting applications specified in /opt/TurboVNC/bin/xstartup.turbovnc
Log file is /home/grass/.vnc/1e0956581827:1.log

MESA: error: ZINK: vkCreateInstance failed (VK_ERROR_INCOMPATIBLE_DRIVER)
glx: failed to create drisw screen

(grass:30): dbind-WARNING **: 01:24:31.709: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
MESA: error: ZINK: vkCreateInstance failed (VK_ERROR_INCOMPATIBLE_DRIVER)
libEGL warning: egl: failed to create dri2 screen
/usr/bin/grass
[2024-11-11][01:25:06][grass::utils][ERROR] [WebsocketManager]: unable to connect to wss://proxy2.wynd.network:4650/: Websocket client timeout
[2024-11-11][01:25:26][grass::utils][ERROR] [WebsocketManager]: unable to connect to wss://proxy2.wynd.network:4444/: Websocket client timeout
[2024-11-11][01:25:46][grass::utils][ERROR] [WebsocketManager]: unable to connect to wss://proxy2.wynd.network:4650/: Websocket client timeout
[2024-11-11][01:25:56][grass][ERROR] Unable to lock WebsocketManager
[2024-11-11][01:26:06][grass::utils][ERROR] [WebsocketManager]: unable to connect to wss://proxy2.wynd.network:4444/: Websocket client timeout
[2024-11-11][01:26:16][grass::utils][ERROR] [WebsocketManager]: reconnection limit exceeded: unable to connect after 4 attempts
[2024-11-11][01:26:16][grass::utils][ERROR] [WebsocketManager]: client reconnection failed
[2024-11-11][01:26:16][grass::utils][ERROR] [start_websocket]: manager could not connect
[2024-11-11][01:26:27][grass::utils][ERROR] [WebsocketManager]: unable to connect to wss://proxy2.wynd.network:4650/: Websocket client timeout
[2024-11-11][01:26:47][grass::utils][ERROR] [WebsocketManager]: unable to connect to wss://proxy2.wynd.network:4444/: Websocket client timeout



```

Thank you

**Comment by engageub** [comment]
Hello,
FYI, grass team mentioned the following in discord group `Traffic has been flowing through the network at an elevated rate. We're working on a fix to improve connection stability.`.
You can use the existing docker image in the script if you wish to get 2X points or continue using the docker image which uses chrome extension. 

![image](https://github.com/user-attachments/assets/e88e82a1-dd43-4235-84b0-3133fe3b4d9c)

Thank you

**Comment by hoainv1807** [comment]
Hi @engageub, I test another docker image desktop version 217heidai/grass and it's work.  but need manually input user/password for each container in UI.
could you look at it and make some test version. I'm fail while try to use in your script :(

with trangoul/grass-desktop, it's not stable and disconnect very frequency

**Comment by engageub** [comment]
Hello @hoainv1807,
Thank you for the suggestion, same errors were shown in docker logs for the suggested docker image.
Both the docker images are using the same latest grass application. 
The issue is with connectivity to grass server and they are aware of it and are going to resolve  the issue.

PFB the logs from 217heidai/grass
```
[xvnc        ] Mon Nov 11 13:04:52 2024
[xvnc        ]  Connections: accepted: /tmp/vnc.sock
[xvnc        ]  SConnection: Client needs protocol version 3.8
[xvnc        ]  SConnection: Client requests security type None(1)
[xvnc        ]  VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
[xvnc        ] Mon Nov 11 13:04:53 2024
[xvnc        ]  VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian bgr888
[app         ] [2024-11-11][13:05:29][grass::utils][ERROR] [WebsocketManager]: unable to connect to wss://proxy2.wynd.network:4650/: Websocket client timeout
[app         ] [2024-11-11][13:05:49][grass::utils][ERROR] [WebsocketManager]: unable to connect to wss://proxy2.wynd.network:4444/: Websocket client timeout
[app         ] [2024-11-11][13:06:09][grass::utils][ERROR] [WebsocketManager]: unable to connect to wss://proxy2.wynd.network:4650/: Websocket client timeout
[app         ] [2024-11-11][13:06:19][grass][ERROR] Unable to lock WebsocketManager
[app         ] [2024-11-11][13:06:29][grass::utils][ERROR] [WebsocketManager]: unable to connect to wss://proxy2.wynd.network:4444/: Websocket client timeout
[app         ] [2024-11-11][13:06:39][grass::utils][ERROR] [WebsocketManager]: reconnection limit exceeded: unable to connect after 4 attempts
[app         ] [2024-11-11][13:06:39][grass::utils][ERROR] [WebsocketManager]: client reconnection failed
[app         ] [2024-11-11][13:06:39][grass::utils][ERROR] [start_websocket]: manager could not connect
[app         ] [2024-11-11][13:06:49][grass::utils][ERROR] [WebsocketManager]: unable to connect to wss://proxy2.wynd.network:4650/: Websocket client timeout


```

**Comment by hoainv1807** [comment]
hi @engageub, if I using more than 1 proxy, only 1 ip connect to grass

**Comment by engageub** [comment]
Hello,
Could you please give a delay of 120 seconds in `properties.conf` file.
Grass container consumes more CPU on start.
If your CPU is not enough, it can cause login issues for  the next containers. 

One more reason could be that you have more proxies and your proxy is beyond the existing list.
Please click on "Load More" button at the bottom of the page.


![image](https://github.com/user-attachments/assets/746369da-fd2a-466b-a6fb-8a4bdfe3b8bd)

Thank you

**Comment by engageub** [comment]
> > Hello, Could you please give a delay of 120 seconds in `properties.conf` file. Grass container consumes more CPU on start. If your CPU is not enough, it can cause login issues for the next containers.
> > One more reason could be that you have more proxies and your proxy is beyond the existing list. Please click on "Load More" button at the bottom of the page.
> > ![image](https://private-user-images.githubusercontent.com/103608400/385671368-746369da-fd2a-466b-a6fb-8a4bdfe3b8bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0ODgzOTksIm5iZiI6MTczMTQ4ODA5OSwicGF0aCI6Ii8xMDM2MDg0MDAvMzg1NjcxMzY4LTc0NjM2OWRhLWZkMmEtNDY2Yi1hNmZiLThhNGJkZmUzYjhiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QwODU0NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDk2MzQzNTljYTE0MDNiMjJlNDE1ODYxNzM4MGU0MmJkYWUzZTBmOWRlMWFhMWEwNzg3YzI0OTg3ZTIxYTUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GYNfdbo3rOmUdSkF2MP03Ab0yPtZ9vhbueGOoRHjQUA)
> > Thank you
> 
> Hi, could you give me the Key to config. Thank you

Hello.
The code has been updated now with default delay of 60 seconds after grass container starts.
Please update internetIncome.sh file.

Thank you

**Comment by hoainv1807** [comment]
@engageub I add sleep 100, run 3 proxies, it doesn't work. 

I see in docket hub has param --port-forward 5900:5900/tcp

is it conflic port when run second grass?

**Comment by engageub** [comment]
Hello,
Could you please check docker logs.
Port forward is required for VNC connection.
Docker containers run in isolated environment so, no port conflict occurs
for internal listening ports.
Usually it takes about a minute for container to be
online.
Please have a look at similar discussion below.
https://github.com/engageub/InternetIncome/discussions/158

Thank you
