### ISSUE TITLE
Multiple accounts, multiple proxies, how to run them

### ISSUE THREAD

**Issue by piqihaha** [engageub/InternetIncome#170]
If I have 3 accounts to run, should I copy the folder InternetIncome into 3 copies, InternetIncome1, InternetIncome2, and InternetIncome3?
like this
Then modify the proxy 
InternetIncome1/proxies.txt
InternetIncome2/proxies.txt
InternetIncome3/proxies.txt
Modify grass ID 
InternetIncome1/properties.conf
InternetIncome2/properties.conf
InternetIncome3/properties.conf
last run
InternetIncome1/internetIncome.sh --start
InternetIncome2/internetIncome.sh --start
InternetIncome3/internetIncome.sh --start
I feel like I did something wrong?

**Comment by engageub** [comment]
Hello,
I don't see any issue with the configuration. Just make sure you have enough resources.
Also, do not try to create accounts for yourself. You can run multiple nodes on same account. But multiple accounts are not usually allowed. 

Thank you

**Comment by engageub** [comment]
Always go inside the folder where internetIncome.sh file is present and start it.
If you are running from outside the current directory will overlap the files.

Thank you

**Comment by piqihaha** [comment]
thank you very much
If I had 500 accounts, it would be a hell of a job

**Comment by engageub** [comment]
There are limits for the number of devices per account in the ReadMe file. 
You may have a look at each application and set the number of  proxies accordingly.

**Comment by piqihaha** [comment]
If I just run grass
Can I run the command like this?
-------------
docker run --name tun-1 --restart=always -v /root/InternetIncome/resolv.conf:/etc/resolv.conf:ro -e EXTRA_COMMANDS='ip rule add iif lo ipproto udp dport 53 lookup main;' -e PROXY="socks5://user:pass@1.1.1.1:6136" -v /dev/net/tun:/dev/net/tun --cap-add=NET_ADMIN -d xjasonlyu/tun2socks:v2.5.2
docker run -d --name grass-1 --platform=linux/amd64 --restart=always --network=container:tun-1 -v /root/InternetIncome/resolv.conf:/etc/resolv.conf:ro -e GRASS_USERNAME="111111@gmail.com" -e GRASS_PASSWORD="111111" trangoul/grass-desktop:latest

docker run --name tun-2 --restart=always -v /root/InternetIncome/resolv.conf:/etc/resolv.conf:ro -e EXTRA_COMMANDS='ip rule add iif lo ipproto udp dport 53 lookup main;' -e PROXY="socks5://user:pass@2.2.2.2:6136" -v /dev/net/tun:/dev/net/tun --cap-add=NET_ADMIN -d xjasonlyu/tun2socks:v2.5.2
docker run -d --name grass-2 --platform=linux/amd64 --restart=always --network=container:tun-2 -v /root/InternetIncome/resolv.conf:/etc/resolv.conf:ro -e GRASS_USERNAME="111111@gmail.com" -e GRASS_PASSWORD="111111" trangoul/grass-desktop:latest

**Comment by engageub** [comment]
The code is open source and you can modify it as you wish on your PC and run it.

**Comment by piqihaha** [comment]
Thank you very much brother

**Comment by engageub** [comment]
Welcome.

**Comment by drdre-lab** [comment]
> There are limits for the number of devices per account in the ReadMe file.

Can you tell me which ReadMe file contains this information? don't find it in yours Readme file

**Comment by engageub** [comment]
> > There are limits for the number of devices per account in the ReadMe file.
> 
> Can you tell me which ReadMe file contains this information? don't find it in yours Readme file

Hello, 
The main page has comparison table. Please scroll down.  The default page shown is from [README.md](https://github.com/engageub/InternetIncome/blob/main/README.md) file.

https://github.com/engageub/InternetIncome


Thank you
