### ISSUE TITLE
Restart.sh

### ISSUE THREAD

**Issue by drdre-lab** [engageub/InternetIncome#171]
Tell me please. Is the script restart.sh working? Does it restart containers? I run the script with Grass containers, but I don't see containers being reloaded. Also, there is no script status or response in the console.
![screen1](https://github.com/user-attachments/assets/d0dcd894-b489-4cd0-bc4b-7dc4d18839c0)
Over time, containers Grass receive a status "Not connected" in the Grass dashbord. Restarting the container manually helps to reconnect the container. And restarting with a script restart.sh does not help. It feels like the containers are not being reloaded.

**Comment by engageub** [comment]
Hello,
Restart.sh is used internally by code. You should not be executing it manually. 
Usually grass containers connect automatically after sometime if they are disconnected. So restarting them manually is not required. 

Thank you

**Comment by drdre-lab** [comment]
I see that my Grass container does not reconnect to the Grass for more than 24 hours. Therefore, i have to manually. After the manual restart container is connected immediately. Thanks for the explanations and for your script

**Comment by engageub** [comment]
Hello,
This is uncommon if they are not connected for 24 hours. 
A temporary restart script was implemented earlier for grass and has been removed later as it was reconnecting automatically. 
To restart all the containers, you will have to use `updateProxies.sh` file. 

If you are using test branch there are multiple options in the `internetIncome.sh` file.
You may use the following to restart all the containers. 

```
sudo bash internetIncome.sh --restart
```

If this is causing much trouble and grass team takes time to resolve, will have to again add restart script for grass till they resolve the issue. 

Thank you

**Comment by engageub** [comment]
Hello,
If you would like to restart grass containers, please use the latest test branch.
They will be restarted every two hours.

https://github.com/engageub/InternetIncome/tree/test

Thank you
