### ISSUE TITLE
MAX_MEMORY

### ISSUE THREAD

**Issue by drdre-lab** [engageub/InternetIncome#172]
Tell me please. How does the MAX_MEMORY function work? Does it kill (stop) the container when the limit is exceeded? or restarts it? Some containers start using more memory over time. And it would be useful to restart the container when the limit is exceeded.

**Comment by engageub** [comment]
Hello,

The MAX_MEMORY setting specifies the maximum RAM limit for each container. In most cases, this is not necessary unless there are memory-related issues, such as memory leaks within the application.

Previously, the Proxylite application experienced such issues, where memory usage gradually increased over time. To mitigate this, the --restart always flag is applied in the configuration, which attempts to automatically restart the container in case of failure.

Similarly, browser-based applications like Adnade and Ebesucher also exhibited gradual memory consumption growth. As a result, these applications are set to restart automatically every one to two hours, following data clearance.

For further insight into the memory consumption of each container, you can use the docker stats command.

Thank you.

**Comment by drdre-lab** [comment]
> For further insight into the memory consumption of each container, you can use the docker stats command.

Thanks. Memory consumption for my Grass containers is gradually increasing. The initial consumption is about 300 MB, over time the consumption increases to 500 MB or more. So I'm looking for a way to restart containers periodically in order to avoid memory overruns and errors "Not Connected".
