### ISSUE TITLE
Unable to find image 'docker:18.06.2-dind' locally 

### ISSUE THREAD

**Issue by moneyckv** [engageub/InternetIncome#176]
Hello admin,
The latest version of Docker is currently 24.0.7-0ubuntu2~20.04.1, but the Docker image used in the internetIncome.sh file is still 18.06.2. This is likely the cause of the error message mentioned in the title.  And does this affect the containers after installation?
I hope the admin updates this soon.  
Thank you, admin.

**Comment by engageub** [comment]
Hello,
This is the common message updated by docker when the image was not downloaded earlier.
Once the image is downloaded, you will not see the message.
That's an info message and not any error. 

Thank you

**Comment by engageub** [comment]
If you find any errors in console, please raise an issue with complete logs displayed on console. 
Closing this with respect to previous comment.

**Comment by moneyckv** [comment]
> Hello, This is the common message updated by docker when the image was not downloaded earlier. Once the image is downloaded, you will not see the message. That's an info message and not any error. So far there were no issues with compatibility with respect to the dind container. The dind containers in the script act as schedulers for few applications like ebesucher and adnade. This will not affect other containers.
> 
> Thank you

Thanks admin.
