### ISSUE TITLE
tun not starting correctly

### ISSUE THREAD

**Issue by warhawk200** [engageub/InternetIncome#177]
![image](https://github.com/user-attachments/assets/54572ee4-c930-43d8-b755-b4145ebb537a)
![image](https://github.com/user-attachments/assets/142fb9fa-4bee-413c-8fbe-f73ae091115e)

getting this issue on oracle cloud 

using proxy from proxy cheap in this format http://00.000.00.000:00000             (in proxies.txt)

Request:  also please add more depin projects (similar to grass and nodepay) like dawn validator , bless network , teneo protocol and blockmesh

**Comment by warhawk200** [comment]
without proxies on , honeygain is starting normally btw

**Comment by engageub** [comment]
Hello,
Please have a look at this issue. The other user also had similar issue and was able to resolve it.
https://github.com/engageub/InternetIncome/issues/173

Thank you

**Comment by engageub** [comment]
Hello,
Could you please uninstall your docker and run the following command to install docker. 

```
sudo bash internetIncome.sh --install
```

Thank you

**Comment by engageub** [comment]
Let me know if the above command resolved the issue. If your Oracle VPS uses arm64 architecture, it requires additional tools to  support amd64 docker images. 
The problem may be with newly installed OS on your VPS or you have installed something which resulted in permissions conflict. 

Regarding Depin Projects, they will be added if docker images are available. 
Alternatively, you can run multiple custom browsers through [test branch](https://github.com/engageub/InternetIncome/tree/test) and install  extensions manually for any new app which uses browser extension.

**Comment by warhawk200** [comment]
> Hello, Could you please uninstall your docker and run the following command to install docker.
> 
> ```
> sudo bash internetIncome.sh --install
> ```
> 
> Thank you
![image](https://github.com/user-attachments/assets/3b4a2dff-52c6-49fb-ad38-dab3be120073)
![image](https://github.com/user-attachments/assets/f50c377c-846e-4cca-8c35-dc850c297840)

looks like its worked , though honeygain seems to be waiting for traffic? 

thanks

**Comment by warhawk200** [comment]
for honeygain i need to turn on proxies only right sir ? and which protocol does honeygain use http or sock5 ?

**Comment by engageub** [comment]
> looks like its worked , though honeygain seems to be waiting for traffic?
Thank you for the confirmation. Did you do anything else before running the command.
Just want to make sure that the command resolved the issue. 

If honeygain shows waiting for traffic for long time, your IP may not be detected as residential.

Thank you

**Comment by engageub** [comment]
> for honeygain i need to turn on proxies only right sir ? and which protocol does honeygain use http or sock5 ?

Yes, you need to turn on proxies if you need to use them. You can use either of the protocols. 

Thank you

**Comment by warhawk200** [comment]
Thanks, is there any guide about how can i use chrome to install extensions manually ?

**Comment by engageub** [comment]
> Thanks, is there any guide about how can i use chrome to install extensions manually ?

There is no separate guide as test branch is for advanced users. The configuration is straight forward. 

1. You will need to use [test branch](https://github.com/engageub/InternetIncome/tree/test).
2. Then set `CUSTOM_CHROME` to `true` in `properties.conf` and start.
3. You will get the access URLs in the mentioned file or through the console with which you can access the browser inside the container. Please refer [this](https://github.com/engageub/InternetIncome/wiki/Frequently-Asked-Questions#-how-to-access-127001-urls-for-ebesucher-or-mystnodes-if-gui-is-not-available-in-linux-) on how to access the URLs.  

Once you get access to the browser, you can use it as regular browser and install the extensions as you would on your desktop.

**Comment by warhawk200** [comment]
thank you for solving all my problems 🙌
