### ISSUE TITLE
[Feature Request]Can you support proxy format like this protocol://ip:port:username:password

### ISSUE THREAD

**Issue by hungf1511** [engageub/InternetIncome#18]
I have a lot of residential proxies but converting them to protocol://username:password@ip:port format is very time consuming

**Comment by engageub** [comment]
Please use the following to convert proxies. 
The script supports proxies  without protocol also for socks5. It autodetects the protocol. 
Replace text, protocol:// with blank value using notepad and then paste the proxies in the website for changing the format.

https://speedproxies.net/proxy-formatter/
https://buyproxies.org/panel/format.php

Thank you

**Comment by hungf1511** [comment]
Oh thanks you so much

**Comment by SkullFace141** [comment]
Hi can you share your proxy provider and review them?

**Comment by engageub** [comment]
@SkullFace141,
Could you please be specific to who the question is being asked since multiple people are present in this conversation. 
Also please elaborate what you mean by review them.

Thank you

**Comment by SkullFace141** [comment]
@hungf1511

**Comment by engageub** [comment]
@hungf1511,
Could you please share the proxy provider which is working fine for residential proxies.

Thank you

**Comment by engageub** [comment]
Please see the following wiki on how to convert them to required format based on different proxy formats

https://github.com/engageub/InternetIncome/wiki/Formatting-proxies-to-user:password@ip:port

Thank you
