### ISSUE TITLE
[Help] Earnapp issue

### ISSUE THREAD

**Issue by hungf1511** [engageub/InternetIncome#19]
Earnapp has problem running too many proxies the generated urls don't work when linking they will say "Device not found". Although I have tried those proxies on the window version and they work great. things started going bad from the 200th proxy onwards not only earnapp but even iproyals had the same problem

**Comment by engageub** [comment]
Hi,
When you started the application, did you see any errors in the console?  Please paste them here.
Do you already have other containers running apart from these 200 proxies.?
Could you please provide the number of proxies used to start the application.
Are you starting all the apps in same folder or using different folders?

Make sure your CPU, memory and diskspace are normal.

Thank you

**Comment by hungf1511** [comment]
I use 50 proxies for each 1 vps 2-8 running only Earnapp and iproyal. The first 4 vps works perfectly but from the 5th vps everything seems wrong. While running it didn't show any errors at first I thought the problem was with the proxy but when I tested them in the windows version they all worked fine.

**Comment by engageub** [comment]
Could you please elaborate what you mean by everything seems to be wrong.  In the 5th VPS do you have problem when the number of containers crossed 200?
Are the proxies in correct format?
Did you reboot your PC or was it restarted automatically?

Thank you

**Comment by engageub** [comment]
Could you please update on this with the output of the commands. 

Thank you

**Comment by Cr4ckPwd** [comment]
<img width="1482" alt="image" src="https://github.com/engageub/InternetIncome/assets/84202581/ee8daf77-d38a-48bc-aa60-10d2547a2936">
@engageub I have same issue

**Comment by engageub** [comment]
Your proxy containers are exited, it means there is a problem with the proxy used. Please make sure your proxies don't have special characters at the end of each line in proxies.txt.
If you combined multiple files or copy pasted into the text file, there are chances that the text inputted are not in the right format and special characters might have been added.
Please open proxies.txt with vi editor in the console and make sure your proxies are in the right format.

Thank you

**Comment by engageub** [comment]
If you have already installed watchtower, please clean up your docker containers and download the script again.
The old script does not work with watch tower. Please download the latest one. 

Thank you

**Comment by Cr4ckPwd** [comment]
<img width="1321" alt="image" src="https://github.com/engageub/InternetIncome/assets/84202581/ce47df87-d399-4f75-a5b5-dc82e30b7fa9">
maybe that is having problem, I'm using the latest version

**Comment by engageub** [comment]
Is this problem only with earnapp or other apps as well?
Could you please enable Logs in properties.conf and use the following command  to see what is going on with earnapp. 
The status shows unhealthy on your PC. When you ran the script did you see any errors on the screen.
Also are your proxies socks5 or http proxies.
Is your OS architecture amd64 or aarch64 or arm64.

```
sudo docker container logs <container name or container id here>
```

The container id is present in 1st column.

Thank you

**Comment by Cr4ckPwd** [comment]
<img width="627" alt="image" src="https://github.com/engageub/InternetIncome/assets/84202581/d05a9be8-c84d-4116-b3c6-600520d21d93">
here is the log of container earnapp

**Comment by Cr4ckPwd** [comment]
![Uploading image.png…]()
tun2socks logs

**Comment by Cr4ckPwd** [comment]
time="2023-06-08T07:08:20Z" level=warning msg="[TCP] dial 104.24.177.7:80: HTTP auth required by proxy"
time="2023-06-08T07:08:20Z" level=warning msg="[TCP] dial 54.221.247.193:80: HTTP auth required by proxy"
time="2023-06-08T07:08:20Z" level=warning msg="[TCP] dial 54.221.247.193:80: HTTP auth required by proxy"
time="2023-06-08T07:08:23Z" level=warning msg="[TCP] dial 34.237.199.147:443: HTTP auth required by proxy"
time="2023-06-08T07:08:26Z" level=warning msg="[TCP] dial 15.204.2.228:80: HTTP auth required by proxy"
time="2023-06-08T07:08:26Z" level=warning msg="[TCP] dial 15.204.2.228:80: HTTP auth required by proxy"
time="2023-06-08T07:08:33Z" level=warning msg="[TCP] dial 34.237.199.147:443: HTTP auth required by proxy"
time="2023-06-08T07:08:35Z" level=warning msg="[TCP] dial 15.204.2.228:80: HTTP auth required by proxy"
time="2023-06-08T07:08:36Z" level=warning msg="[TCP] dial 15.204.2.228:80: HTTP auth required by proxy"
time="2023-06-08T07:08:43Z" level=warning msg="[TCP] dial 34.237.199.147:443: HTTP auth required by proxy"
time="2023-06-08T07:08:45Z" level=warning msg="[TCP] dial 15.204.2.228:80: HTTP auth required by proxy"
time="2023-06-08T07:08:46Z" level=warning msg="[TCP] dial 15.204.2.228:80: HTTP auth required by proxy"

**Comment by engageub** [comment]
Its clear that you have problem with your proxy. Please make sure your credentials are correct.
Also are you using http or https?

Thank you

**Comment by Cr4ckPwd** [comment]
how can I direct messenger to you, this proxy work with Honeygain too

**Comment by engageub** [comment]
Are you mentioning that you used honeygain with the same proxies using this script? If not
can you try using honeygain also in the same folder and see if it is online to confirm if its not proxy issue.
The logs confirm its a problem with authentication. Do you have special characters in your username or password. 
Use the same proxies to start earnapp and honeygain in the same properties.conf file.
Use proxylite or pawns since they don't have limitations with the number of proxies and you will see them immediately if they are online.

Thank you

**Comment by Cr4ckPwd** [comment]
my proxy input in file proxies.txt
http://huhuhu:huhuhu@dad134.domain.com:10052

**Comment by engageub** [comment]
The format is correct. But there seems to be some problem with your proxy. 
Is this working in browser or other apps using the script. 
 

Thank you

**Comment by engageub** [comment]
Please note that issues with proxies is not supported here. 
The script is working as expected.

**Comment by engageub** [comment]
@hungf1511,
Please update to the latest version by downloading the script from github.
Also, could you please share the proxy provider where residential proxies were working.

Thank you
