### ISSUE TITLE
Multi proxy issue

### ISSUE THREAD

**Issue by hungf1511** [engageub/InternetIncome#2]
I have issue when i run your with multi proxy residential all device will be offline

**Comment by engageub** [comment]
Could you please let me know which application and may I know if you have sufficient CPU and memory on your device.
Thank you

**Comment by hungf1511** [comment]
I run it with vm 16 core and 16gb ram for 50 proxy

**Comment by engageub** [comment]
okay. May I know which application or are you running all applications?
Are all applications offline?

Thank you

**Comment by hungf1511** [comment]
All application when it run 5 min or 10 min

**Comment by engageub** [comment]
okay. May I know if you are running 500 instances of docker in total?
Does you ping test succeed for example the following command in terminal.
**ping google.com** 

Also, could you please run **sudo docker container ls**  command in terminal and see if the processes are still working.

Docker has a limitation of 1023 instances per network. 

Thank you

**Comment by engageub** [comment]
Could you also enable logs in the properties file. There could also be a possibility that your proxies are slow.
Could you please check if you have sufficient SWAP space also. Please check your RAM after starting the applications. 

Thank you

**Comment by engageub** [comment]
Thank you. 
May I know how you did ping test. From terminal?
Could you please follow my previous step and let me know if after stopping watchtower and starting it is working fine.
Bitping or iproyals or proxylite dashboard shows if the proxies are online or not.

Thank you

**Comment by engageub** [comment]
Can you share your screen using https://www.screenleap.com/, so we can understand better and resolve this quickly.

Thank you

**Comment by hungf1511** [comment]
https://screenleap.com/nguyen_hung

**Comment by engageub** [comment]
Yes, I see your screen, can we chat in the following link https://codeshare.io/qPekMz

Thank you

**Comment by engageub** [comment]
The issue was with high CPU usage of more than 92%. Just make sure your CPU usage is below 80%.
Closing the ticket as discussed.  
Please reopen the ticket if the issue still persists after sometime.

Thank you
