### ISSUE TITLE
UUID does not exist, creating UUID

### ISSUE THREAD

**Issue by Cr4ckPwd** [engageub/InternetIncome#20]
UUID does not exist, creating UUID when Create earnapp

**Comment by engageub** [comment]
Could you please elaborate what you are trying to convey.

Thank you

**Comment by engageub** [comment]
The script is working as expected. The messages mean no error. Closing this since it is working as expected. 
Please describe the issue in detail if the devices are offline when added to dashboard. 

Thank you
