### ISSUE TITLE
Update account info

### ISSUE THREAD

**Issue by yesyeahvh123** [engageub/InternetIncome#21]
Hello, thanks for creating this script. I'm a newbie so I have a question that when the container already running and I edit the file properties.conf (edit/add account), what command should I run to update again, thanks

**Comment by engageub** [comment]
Hi,

You need to delete and start the script if you change properties.conf file.
Use --delete to delete and --start to start the container.

Thank you

**Comment by engageub** [comment]
Please see the main page for to start and delete. If you change the account, make sure you delete backups.
https://github.com/engageub/InternetIncome

Thank you
