### ISSUE TITLE
traffmonetizer notwork

### ISSUE THREAD

**Issue by Cr4ckPwd** [engageub/InternetIncome#24]
A few days ago, it was working perfectly fine, but today when I set it up again, it encountered an error. All operations, containers, and proxies are functioning properly. The containers run without any issues, but Traffmonetizer doesn't detect any devices. Please help me check it again.

**Comment by engageub** [comment]
Could you please see if  you used double quotes in properties.conf file.
Also please enable logs in properties.conf to see if there any issues in containers.

Thank you

**Comment by engageub** [comment]
Could you please see if you are using the latest version.

Thank you

**Comment by Cr4ckPwd** [comment]
I tried with a proxy without a user pass that worked, but having a user pass it is not work

**Comment by Cr4ckPwd** [comment]
> see if you are using the latest ve

yes latest version

**Comment by Cr4ckPwd** [comment]
how can I send you DM, I will give you my proxy

**Comment by engageub** [comment]
No. Testing will not be done on proxies if you have issue with proxies.
Please make sure you are choosing the right date in proxies.

Thank you

**Comment by engageub** [comment]
Also, enable logs in properties.conf file and look into container logs if there are any proxy issues or auth issues.

Thank you

**Comment by engageub** [comment]
The latest version works without  double quotes also.  This is just an info.

**Comment by engageub** [comment]
Closing this since there is no further update on this. Please reopen if there is still issue and update the logs as mentioned.
Thank you
