### ISSUE TITLE
Traffmonetizer with proxy

### ISSUE THREAD

**Issue by Cr4ckPwd** [engageub/InternetIncome#26]
Along with a proxy, if I use it to run with Honeygain, it works fine without any errors.
However, when I run it with Traffmonetizer using the same proxy, it reports the following error:

```
time="2023-06-17T15:06:55Z" level=warning msg="[TCP] dial 144.76.194.78:443: HTTP auth required by proxy"
time="2023-06-17T15:06:56Z" level=warning msg="[TCP] dial 168.119.91.41:443: HTTP auth required by proxy"
time="2023-06-17T15:06:57Z" level=warning msg="[TCP] dial 168.119.91.41:443: HTTP auth required by proxy"
time="2023-06-17T15:06:58Z" level=warning msg="[TCP] dial 168.119.91.41:443: HTTP auth required by proxy"
```

**Comment by engageub** [comment]
Hi,
The latest version has been downloaded and there are no such errors in the logs. It looks like an issue with your proxy blocking something.
FYI: Traffmonetizer was updated 2 days back.  https://hub.docker.com/r/traffmonetizer/cli
Are you using http or socks5 proxy.

Thank you

**Comment by engageub** [comment]
Closing this since the code is working as expected. The responsibility of the code is only to create isolated containers and redirect them through proxies. Any issue with proxies is not supported.
Thank you
