### ISSUE TITLE
issue docker check work

### ISSUE THREAD

**Issue by contidz** [engageub/InternetIncome#29]
hi, when running the script, how can i check if docker is working or not?
i use ubuntu 20.04
thank you

**Comment by engageub** [comment]
Hi,
Docker is automatically installed with the commands mentioned here https://github.com/engageub/InternetIncome 
Please follow the steps mentioned in the read me of above link about prerequisites.
If there is any issue you will see it in console logs while running it. It will throw errors about unsuccessful installation. 

However you may run the following command to see the output to test. If you see the message " Hello from Docker!". Your docker is installed and is working fine.

```
sudo docker run --rm hello-world
```



Thank you

**Comment by engageub** [comment]
If you wish to debug on the containers running with this script, please enable logs in properties.conf file.
Then start the script and follow docker guidelines on to check logs for docker containers. 

Thank you
