### ISSUE TITLE
Socks5 UDP Mysterium nodes

### ISSUE THREAD

**Issue by SkullFace141** [engageub/InternetIncome#3]
Hi

can you explain how can Mysterium nodes work on socks5?
please add https://cashraven.io to your list, its not yet supported on linux but support will be added this year.
please also create a wiki with documentation.

**Comment by engageub** [comment]
Hi,
The queries have been answered in FAQ Section for Mysterium node. 
Your Socks5 needs to support UDP protocol, else your node shows "Monitoring Failed", even if your node is accessible in the browser. 
If you are going to setup proxies on your own, make sure UDP is enabled, else check with your provider if UDP is enabled for socks5. Most of the providers online are providing TCP enabled proxies only. 
If you have already used it using direct connection, the process is similar except the URLs are stored in mysterium.txt file in same folder.
You will need to visit the URLs using browser to setup the node initially. 
You need to make payment of $1 or ~0.22 MYST to start the node.  
For every node you setup, you have to make payment for that node. 
The data is stored in "mysterium-data" folder and you have to take backup if you want to restart again else you need to make payment again for new node. 

Regarding cashraven, Thank you for the link, I have the app installed in mobile phone and is active but I hardly see any data. However I will add it to the list.

Thank you

**Comment by SkullFace141** [comment]
can you make it use 1 honeygain account per 10 proxies?
can you add support for swarmbytes?

**Comment by SkullFace141** [comment]
my provider supports UDP but i dont understand how is it going to work technically for incoming connections.

**Comment by engageub** [comment]
> can you make it use 1 honeygain account per 10 proxies? can you add support for swarmbytes?

Yes, with honeygain you can add 10 devices per account. Swarmbytes is different.  You need to have atleast 250 IPS and they provide you with setup.

Thank you

**Comment by SkullFace141** [comment]
I meant one instance with multiple honeygain accounts setup in the same config file

**Comment by engageub** [comment]
> my provider supports UDP but i dont understand how is it going to work technically for incoming connections.
It uses both TCP and UDP. You can use it with direct VPS also. 
You may try it with direct connection then switch to proxies later. 
Thank you

**Comment by engageub** [comment]
> I meant one instance with multiple honeygain accounts setup in the same config file

It creates each instance for each proxy specified in the proxies.txt file.

**Comment by SkullFace141** [comment]
so i need 5 copies each with 10 proxies and different honeygain account?

**Comment by SkullFace141** [comment]
can you randomize device name with auto increments for example, ubuntu1, ubuntu2...etc

**Comment by engageub** [comment]
The device can be changed from ubuntu to anything you prefer. But the numbers are added incrementally as we do normally to identify the number of devices added.
You can modify the code accordingly after the download. Its upto you how you use it. 

Please read the FAQ's if you have any queries before raising issue. 

Thank you

**Comment by SkullFace141** [comment]
thanks

**Comment by engageub** [comment]
> so i need 5 copies each with 10 proxies and different honeygain account?

As mentioned in the FAQ, you can create multiple folders and run it for multiple users. Honeygain does not allow this for single user.
