### ISSUE TITLE
Unable to pull peer2profit image

### ISSUE THREAD

**Issue by SkullFace141** [engageub/InternetIncome#34]
Starting Peer2Profit container..
Unable to find image 'peer2profit/peer2profit_linux:latest' locally
docker: Error response from daemon: pull access denied for peer2profit/peer2profit_linux, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
Failed to start container for Peer2Profit..

**Comment by engageub** [comment]
Peer2profit has removed official support for docker.
If you already have the container you will be able to use it. Else you can't.

Please see reference:
https://github.com/engageub/InternetIncome/issues/32

Thank you

**Comment by SkullFace141** [comment]
https://hub.docker.com/r/enwaiax/peer2profit

**Comment by engageub** [comment]
It is not working. There are many users who published custom versions. They may require to update it.
If you know anything that's working for peer2profit let me know. 
If you have proxies with username and password you can add them to peer2profit dashboard. 
Thank you
