### ISSUE TITLE
updateproxies.sh is broken and needs update

### ISSUE THREAD

**Issue by SkullFace141** [engageub/InternetIncome#36]
updateproxies.sh is broken and needs update as the txt file for tun containers no longer exists

**Comment by engageub** [comment]
Could you please share screenshot. The script only works when the containers are already running and not after using --delete option.

Thank you

**Comment by SkullFace141** [comment]
yes the containers were running

**Comment by engageub** [comment]
Did you update any container and restarted it?
Please share the console screenshot or logs to understand this better.
Thank you

**Comment by engageub** [comment]
This was due to bug in dependent team and they have not updated it yet.
Please update the code now and let me know if its working fine

https://github.com/xjasonlyu/tun2socks/issues/266

Thank you
