### ISSUE TITLE
Problem with Tun2socks (?)

### ISSUE THREAD

**Issue by Tutez-64** [engageub/InternetIncome#39]
Hello, I've successfully used your project on Windows (WSL) and on a VM, but for some reason when I'm trying to use it on a server proxies aren't working.
They are all fresh Debian installations (11.7-12) and are using the same files from your project. Here are some logs from the server:

Pawns: 
> Post "https://api.iproyal.com/v1/users/login": dial tcp: lookup api.iproyal.com on 8.8.8.8:53: read udp {server_ip}:47994->8.8.8.8:53: i/o timeout
> Post "https://api.iproyal.com/v1/users/login": dial tcp: lookup api.iproyal.com on 8.8.8.8:53: read udp {server_ip}:48060->8.8.8.8:53: i/o timeout
[...]

Tun2socks:
> time="2023-07-15T02:04:12Z" level=info msg="[DIALER] set fwmark: 0x22b"
time="2023-07-15T02:04:12Z" level=info msg="[STACK] tun://tun0 <-> socks5://{proxy_ip}:{proxy_port}"
time="2023-07-15T02:05:40Z" level=warning msg="[TCP] dial 158.247.221.15:80: connect to {proxy_ip}:{proxy_port}: dial tcp {proxy_ip}:{proxy_port}: i/o timeout"
time="2023-07-15T02:05:45Z" level=warning msg="[TCP] dial 158.247.221.15:80: connect to {proxy_ip}:{proxy_port}: dial tcp {proxy_ip}:{proxy_port}: i/o timeout"
[...]

No app is working.
If I disable the use of proxies, it is working.
The proxy is not the problem, as it is working on other devices (and on this one, `curl -x {proxy_ip}:{proxy_port} ipinfo.io/ip` works perfectly).
I've tried redoing a fresh installation, disabling the firewall, making changes on the 3 devices, but nothing made any difference.

**Comment by engageub** [comment]
Hello,
Could you please see if 8.8.8.8 DNS is working directly from your PC.
To confirm this, can you run the following command and paste the output.

```
nslookup google.com 8.8.8.8
```

**Comment by Tutez-64** [comment]
`nslookup google.com 8.8.8.8`
>Server:         8.8.8.8
Address:        8.8.8.8#53

>Non-authoritative answer:
Name:   google.com
Address: 142.250.185.238
Name:   google.com
Address: 2a00:1450:4001:813::200e

**Comment by engageub** [comment]
So there is no problem with DNS being blocked on your IP. 
Can you remove IP table rules on your PC then restart docker.
Run the commands sequentially and make sure your existing docker containers are not running. 
```
sudo iptables -F
sudo iptables -X
sudo iptables -t nat -F
sudo iptables -t nat -X
sudo iptables -t mangle -F
sudo iptables -t mangle -X
sudo iptables -t raw -F
sudo iptables -t raw -X
sudo service docker restart
```

**Comment by engageub** [comment]
Also, make sure you are using the latest version of Internet Income from github.
Thank you

**Comment by engageub** [comment]
Hi,
You may also follow this to resolve firewall issues. There was an issue in tun2socks v.2.5.1. If you are using older version of Internet Income script, you may face issues. Please update the latest from github.
Closing this. Please reopen if you still see issues after following the commands.

https://www.digitalocean.com/community/tutorials/how-to-list-and-delete-iptables-firewall-rules#flushing-all-rules-deleting-all-chains-and-accepting-all


Thank you

**Comment by Tutez-64** [comment]
Unfortunately, I've tried everything you sent but nothing seems to be making a difference. I'm using the latest version.
It's working on my VM and on WSL, and even when I copy these files to my server it stops working.
I'm using an Hetzner's dedicated server. Maybe you could order one and see by yourself? You can cancel in the first 14 days and get your money back (if they even took it, I think they only do after a few weeks) no question asked.
Or I can send you the credentials to my server on Discord.

**Comment by engageub** [comment]
Can you DM here https://www.instagram.com/engageub/ and use screenleap.com to share the screen. I am online now
Thank you

**Comment by Tutez-64** [comment]
I don't think I can DM you on Instagram (but I never use it so maybe I'm just dumb) so I DMed you on Discord
