### ISSUE TITLE
docker not working

### ISSUE THREAD

**Issue by contidz** [engageub/InternetIncome#44]
I get this error while running, please help me how to fix it

Error response from daemon: pull access denied for traffmonetizer/cli, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Unable to find image 'traffmonetizer/cli:latest' locally
docker: Error response from daemon: pull access denied for traffmonetizer/cli, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 
![image](https://github.com/engageub/InternetIncome/assets/137675836/0de336e3-6028-498f-b7cc-c8e477e4211f)
'docker run --help'.

**Comment by engageub** [comment]
Hi,
I see that traffmonetizer has removed support for dockerhub. The following url does not exist. 
https://hub.docker.com/r/traffmonetizer/cli 

Thank you

**Comment by contidz** [comment]
is there any way to fix this bro?

**Comment by contidz** [comment]
![image](https://github.com/engageub/InternetIncome/assets/137675836/a0b6764d-0a56-4404-8002-8100c800c3bc)
i have barked lines 316,317,318 seems to have been removed by traff, i am trying to run at proxylite website i want you to check if it works or not

**Comment by engageub** [comment]
If you are seeing the proxies online with different locations it indicates it is working fine. 

Thank you

**Comment by contidz** [comment]
Traffmonetize, repacket is currently not working bro

**Comment by engageub** [comment]
Repocket has the same issue as traffmonetizer and it is not available in docker now. 
Please follow their official discord channel for updates.
https://hub.docker.com/r/repocket/repocket
https://discord.com/channels/953847091736760320/1034409095995871272

Thank you

**Comment by engageub** [comment]
Update from repocket team
![image](https://github.com/engageub/InternetIncome/assets/103608400/68e396dc-cdb6-4669-b361-4410f391e39c)

**Comment by contidz** [comment]
Thank bro

**Comment by contidz** [comment]
the url seems to have been updated again, please update to the new url script
thank
https://hub.docker.com/r/traffmonetizer/cli_v2

**Comment by engageub** [comment]
Thank you for checking on this. Could you please let me know how you got the updated url. Is it official or someone updated it. Did you get it from traffmonetizer support. 

Thank you

**Comment by contidz** [comment]
you can go to the traff homepage to download it it's official on the homepage
thank

**Comment by contidz** [comment]
hope you can add it to the script as quickly as possible

**Comment by engageub** [comment]
Yesterday they had the old url. Looks like they updated today.

**Comment by contidz** [comment]
yes can you edit the script again by adding a new url

**Comment by contidz** [comment]
please let me know how long you need to update the new url
thank

**Comment by engageub** [comment]
Could you please update and let me know if its working now. Please download it again

**Comment by contidz** [comment]
I will reply within 30 minutes
thank you

**Comment by engageub** [comment]
Awaiting update on this since this has not been tested and only changes were made based on the name. 
Thank you

**Comment by contidz** [comment]
![image](https://github.com/engageub/InternetIncome/assets/137675836/8f308496-12ae-465d-bb9d-3717d3321082)
![image](https://github.com/engageub/InternetIncome/assets/137675836/21f0df62-5bd7-4061-bebe-bc9df7df9fc2)
I checked, it works fine, thank you for updating the script again and supporting me!

**Comment by engageub** [comment]
Thank you for the confirmation. There was an update now again after this to remove special characters from properties.conf and proxies.txt file, so you don't have to run sed command from now on to remove special characters.

Thank you

**Comment by contidz** [comment]
Thank you, Good !

**Comment by engageub** [comment]
Closing this since the update has been made for traffmonetizer and it will be updated again once repocket updates their images in dockerhub.
