### ISSUE TITLE
share tool mutil traffmonetizer

### ISSUE THREAD

**Issue by contidz** [engageub/InternetIncome#45]
I found this tool, but it seems to have a bit of a connection problem, after running the tool, it will automatically turn off after a few minutes, I share it hope you can edit it and share it with everyone. People
thank
https://www.upfilemienphi.com/vi/bjlD1TnfkbK

**Comment by engageub** [comment]
Could you please let me know what it is and what this tool does and how does it benefit more from the existing script.

Thank you

**Comment by contidz** [comment]
it is a traffmonetizer multi-tab opener that adds proxy to each tab, it works on windows os, it seems it's easier to use with windows to get speed, you can download it to verifiable, but only used for a few minutes and will be exited because of an error

**Comment by engageub** [comment]
The scripts published here are linux compatible. So I will not be adding it here since the official version is already used in the script.  Anything that's not unofficial or not working consistently will not be published. 

Thank you

**Comment by contidz** [comment]
The tool is for reference only, thank you for replying to me

**Comment by engageub** [comment]
It would be better if there are such tools developed for other websites like peer2profit or trafficearn which support windows.

**Comment by engageub** [comment]
Closing this since this is not an issue.
Thank you
