### ISSUE TITLE
i get docker error can't start

### ISSUE THREAD

**Issue by contidz** [engageub/InternetIncome#46]
tarting..
USE_PROXIES is enabled, using proxies..
Starting Proxy container..
v2.5.0: Pulling from xjasonlyu/tun2socks
Digest: sha256:3e8ea391021663ae2edf9fbee9cb2d08087444e646eab468ea2ccbb260f1f6c1
Status: Image is up to date for xjasonlyu/tun2socks:v2.5.0
docker.io/xjasonlyu/tun2socks:v2.5.0
d35c31d5787332a44fc3fc31a7d0d770a4371ce2cbc3c4060fadfebfada30917
tun73d4d7b15bfefa13c4a035fa16bb99ed1
OCI runtime exec failed: exec failed: unable to start container process: error executing setns process: exit status 1: unknown
Mysterium Node is not enabled. Ignoring Mysterium..
Ebesucher username is not configured. Ignoring Ebesucher..
BitPing Node is not enabled. Ignoring BitPing..
Repocket Email or Api is not configured. Ignoring Repocket..
Traffmonetizer Token is not configured. Ignoring Traffmonetizer..
ProxyRack Api is not configured. Ignoring ProxyRack..
Starting IPRoyals container..
latest: Pulling from iproyal/pawns-cli
Digest: sha256:0409cc5aa1726bdd8680cfe7d8a02822a16f3468021ecd9c703f4bd790bb9431
Status: Image is up to date for iproyal/pawns-cli:latest
docker.io/iproyal/pawns-cli:latest
docker: Error response from daemon: Container d35c31d5787332a44fc3fc31a7d0d770a4371ce2cbc3c4060fadfebfada30917 is restarting, wait until the container is running.
Failed to start container for IPRoyals..
Honeygain Email or Password is not configured. Ignoring Honeygain..
Peer2Profit Email is not configured. Ignoring Peer2Profit..
PacketStream CID is not configured. Ignoring PacketStream..
Proxylite is not configured. Ignoring Proxylite..
Earnapp is not enabled. Ignoring Earnapp..
Starting Proxy container..
0e26b5bf6fed536f0dd495211eaf8d034ae82315576f1693fbaa439a7f20d359
tun73d4d7b15bfefa13c4a035fa16bb99ed2
OCI runtime exec failed: exec failed: cannot exec in a stopped container: unknown
Starting IPRoyals container..
docker: Error response from daemon: Container 0e26b5bf6fed536f0dd495211eaf8d034ae82315576f1693fbaa439a7f20d359 is restarting, wait until the container is running.
Failed to start container for IPRoyals..
Starting Proxy container..
5f2682859631321196c9fd4b47e225d7c1c7656014ee1d7eb00734688cefa50f
tun73d4d7b15bfefa13c4a035fa16bb99ed3
SSOCI runtime exec failed: exec failed: cannot exec in a stopped container: unknown
SSSStarting IPRoyals container..
docker: Error response from daemon: Container 5f2682859631321196c9fd4b47e225d7c1c7656014ee1d7eb00734688cefa50f is restarting, wait until the container is running.

**Comment by engageub** [comment]
Hi,
Looks like there is issue with your proxy configuration.
Please make sure you follow the correct format. 
Open proxies.txt file and make sure they are correct. 

Thank you

**Comment by contidz** [comment]
![image](https://github.com/engageub/InternetIncome/assets/137675836/4bb7b193-68e5-468c-81b2-4b581c97e4fa)
do you know what the problem i am having.
I run earnapp when I paste the link into my account, I get this error

**Comment by engageub** [comment]
May be you tried to add too many devices at once or device limit has been reached. 
You may check with earnapp support on this.
Was the previous issue related to docker solved?
Thank yo

**Comment by engageub** [comment]
Closing this since this is not an issue with the script. Please reopen if you see any issues further.
