### ISSUE TITLE
[Feature Request]Ebesucher reliability issues

### ISSUE THREAD

**Issue by x11r6** [engageub/InternetIncome#51]
Hello, the Ebesucher browser sometimes needs user intervention to click on "Surf now!" and to solve a captcha(see attached image). I believe it has something to do with the erasing of the cookies.
I also think there's the need for something like the "Ebesucher restarter", a tool that actively monitors that the autosurfer is working properly, and if it's not it should just kill the browser and start over. There's an Ebesucher API to check whether a surflink is producing BTP or not.

![ebesucher](https://github.com/engageub/InternetIncome/assets/25671232/fcf6aefc-b943-4e8d-910a-8301213f8508)

**Comment by engageub** [comment]
Hi,
There are various reasons why this happens. If you not using residential proxy or if you are using IPs from same subnet this may happen. You will need to solve the captcha once and let it continue surfing.
This does not usually happen with German proxies. 

Thank you

**Comment by x11r6** [comment]
Hello, I'm using a German residential proxy, but this is happening anyway every now and then. Would it be possible to user the addon "buster" to automatize the captcha solving?

**Comment by engageub** [comment]
Hi,
Yes, I already have this implemented on my pc since I was using non-residential proxy. 
When this happens, usually earnings are not good on such IPs. 
Recaptcha Solver using audio is already available, so it will be added soon. 
Changing this to Feature request to add recaptcha solver using audio. 

Thank you

**Comment by engageub** [comment]
Changes have been pushed to test branch for chrome browser. To use it, set the following value to true in properties.conf file

```
EBESUCHER_USE_CHROME=true
```

https://github.com/engageub/InternetIncome/tree/test


Thank you
