### ISSUE TITLE
I got this error when running about 300 containers

### ISSUE THREAD

**Issue by hieunguyen8794** [engageub/InternetIncome#53]
I got this error when running about 300 containers
My computer has 2 cpu, 4gb ram configuration. And only running 3gb of ram when this error appeared. Is this an issue in the script?

docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc did not terminate successfully: exit status 2: unknown. Failed to start container for proxy. Exiting..

**Comment by engageub** [comment]
Hi,
Could you please check your available RAM space and CPU when this happens.  
Also make sure the format for the proxy given is correct in proxies.txt file
Please check the line number 301 in proxies.txt file and make sure it is in correct format.
In addition to this, you may also want to check the number of docker containers running by using the following command. By default you can run upto 1023 containers on a single network bridge. 
```
sudo docker container ls -a | wc -l
```
Please note that the script is working as expected. 
There is no limit mentioned in the script. It depends on docker limitations and your available resources. 

Thank you

**Comment by engageub** [comment]
Closing this since the script is working as expected. Please feel free to reach out for further queries.
Thank you

**Comment by hieunguyen8794** [comment]
Like I said, there are still plenty of resources. And I tried getting a proxy from 301 onwards to run on another computer and it still works normally.

**Comment by hieunguyen8794** [comment]
![image](https://github.com/engageub/InternetIncome/assets/25577311/0f47a0ff-daf8-49e6-bbe9-24a14715b277)
![image](https://github.com/engageub/InternetIncome/assets/25577311/0eaf3c44-05be-47e1-9a40-21fad7b1c43d)

**Comment by hieunguyen8794** [comment]
@engageub Please try running at this number of proxies, I think you will encounter the same situation

**Comment by engageub** [comment]
I have already ran it with 1000 proxies earlier. May I know which docker version you are using and how you are verifying the resources available. As mentioned the code does not have any limitation with respect to the number of containers.

Is 15% the available cpu or utilized cpu.

Can you run the following command and paste the output to see the limitation on your network. There are work arounds to overcome the limit by creating new network and using that network for containers. 

```
sudo docker network inspect bridge
```

Thank you

**Comment by engageub** [comment]
Hi,
Please refer to this discussion also.
https://github.com/engageub/InternetIncome/discussions/50#discussioncomment-7027048
Thank you
