### ISSUE TITLE
earnapp not working

### ISSUE THREAD

**Issue by friendlyBrandon** [engageub/InternetIncome#54]
Hey, my containers of earnapp are all unhealthy and not working.

**Comment by engageub** [comment]
Hi,
Does your dashboard show something regarding your IP address?
Is this the first time you are running or were you already using it earlier?
Could you please take a screenshot. 
If its from earnapp dashboard, please click on the node to see the reason. 

Thank you

**Comment by friendlyBrandon** [comment]
There is no error, they just show up as offline, same for some other apps.

**Comment by friendlyBrandon** [comment]
I have 1351 containers running and 139 are unhealthy. Basically not working.

**Comment by friendlyBrandon** [comment]
![image](https://github.com/engageub/InternetIncome/assets/81375538/d54948bc-2742-49b5-97cd-f9e9f77478d8)
![image](https://github.com/engageub/InternetIncome/assets/81375538/d5983451-97a8-4d54-a988-41521bdbcd17)
![image](https://github.com/engageub/InternetIncome/assets/81375538/b914d3f1-4ab9-4b0e-9f16-3615726d0364)

**Comment by friendlyBrandon** [comment]
If you wish to contact me on Discord for faster responses and clearer responses, please add me. friendlyBrandon

**Comment by engageub** [comment]
Hi,
Thank you for providing the screenshots.
Could you please let me know if you are running it from same host. 
Were the hosts online earlier and not now?
Does your PC have enough resources like %CPU, %RAM, %diskspace
Are your proxies working fine.
If you are running from same host, please note that there may be limitations in docker network to 1023 containers on same network.
Also note that the script is working as expected and there is no limit mentioned in the script with respect to the number of containers. 

Thank you

**Comment by engageub** [comment]
> ![image](https://user-images.githubusercontent.com/81375538/270161127-d54948bc-2742-49b5-97cd-f9e9f77478d8.png) ![image](https://user-images.githubusercontent.com/81375538/270161146-d5983451-97a8-4d54-a988-41521bdbcd17.png) ![image](https://user-images.githubusercontent.com/81375538/270161154-b914d3f1-4ab9-4b0e-9f16-3615726d0364.png)

I do not know from where the first and third screenshot are obtained. Screenshot 1 and screenshot 3 have discrepancies in the number of devices.

**Comment by engageub** [comment]
> If you wish to contact me on Discord for faster responses and clearer responses, please add me. friendlyBrandon

Thank you. But lets keep this here so that others would know if there is a potential issue and decide on what needs to be done.

Thank you

**Comment by friendlyBrandon** [comment]
It is all running on the same server,
Specs are:
Ryzen 5 3600
64GB RAM
1TB SSD
1gbps internet.

**Comment by engageub** [comment]
So you are running more than 1023 proxies on same network and server?
Are the nodes not working after 1023 containers have been started?
Docker has a network limitation with respect to the number of containers on same network. 

Thank you

**Comment by friendlyBrandon** [comment]
I am running about 170 proxies.

**Comment by engageub** [comment]
> I am running about 170 proxies.

If you are running only 170 proxies and have not created new node Ids and are using existing nodes in the dashboard.  Please enable logs from properties.conf and start the containers. Then look into earnapp docker logs to see if there are any errors.


Thank you

**Comment by friendlyBrandon** [comment]
I will be able to do that in about 90minutes.

**Comment by friendlyBrandon** [comment]
Hey, do you mean the logs that come from starting the app or just the logs after you ran it and are starting the earnapp container?

**Comment by friendlyBrandon** [comment]
![image](https://github.com/engageub/InternetIncome/assets/81375538/e4551ced-a3df-4c1a-b62f-c5c4ad5c0558)

**Comment by engageub** [comment]
> ![image](https://user-images.githubusercontent.com/81375538/270172227-e4551ced-a3df-4c1a-b62f-c5c4ad5c0558.png)

Thank you for the logs. These are the logs mentioned. You will need to see which container is having issue and look into logs for any connectivity issue. 
Please compare them them with healthy container and unhealthy host to see the difference. 

Thank you

**Comment by friendlyBrandon** [comment]
Okay, one second.

**Comment by friendlyBrandon** [comment]
That was unhealthy, this one is healthy:
![image](https://github.com/engageub/InternetIncome/assets/81375538/6bb7b5ee-565f-479d-a9d4-b66b3f76b4e9)

**Comment by engageub** [comment]
Looks like the requests were throttled or there was some connectivity issue.
Can you try restarting the unhealthy container and monitor the logs again. To restart the container, please use the following command.
Replace the container_name below and remove the parenthesis <> before running. 

```
sudo docker restart <container_name>
```

**Comment by friendlyBrandon** [comment]
![image](https://github.com/engageub/InternetIncome/assets/81375538/906d2277-d0f6-44a9-b6b4-d5901f03fe90)
Now I keep on getting this:
![image](https://github.com/engageub/InternetIncome/assets/81375538/6e28739f-c0ec-4f85-b367-7164754ae831)

**Comment by friendlyBrandon** [comment]
Again, unhealthy.

**Comment by friendlyBrandon** [comment]
Okay, I have a better idea, il reset it and redo my proxy list since I have 20 IPs that are whitelisted to my IP. I will put them to credentials now.

**Comment by engageub** [comment]
Is your proxy working fine? 
```
sudo docker exec -it <EARN_APP_CONTAINER> sh 
```

You will be logged into earnapp shell. Then check if connectivity is available in the container to see if your proxy is working fine.

```
wget -O - ifconfig.me/all
```

The above command will give the output of your proxy ip if it is working fine.

**Comment by friendlyBrandon** [comment]
Okay so I redid everything, could have been that I put HTTP instead of SOCKS5 or the IP auth and not putting a username and password in for some proxies.

**Comment by friendlyBrandon** [comment]
I am currently waiting for everything to be created again, please give it some time.

**Comment by engageub** [comment]
As mentioned the script is working as expected. Please see if there is a pattern you can identify with the unhealthy hosts based on the proxies you provided in proxies.txt file.

Thank you

**Comment by friendlyBrandon** [comment]
Once everything is up for a little bit we will see if it is the proxies or the issue with the containers. I also noticed it with repocket that the peers went slowly down.

**Comment by friendlyBrandon** [comment]
wget -O - ifconfig.me/all
Does not work on any earnapp docker container.

**Comment by engageub** [comment]
> wget -O - ifconfig.me/all Does not work on any earnapp docker container.

What error do you see. wget is not available inside the container?

Thank you

**Comment by friendlyBrandon** [comment]
It just keeps on retrying.

**Comment by engageub** [comment]
Its working here without issue. It means your proxy is not working.

**Comment by engageub** [comment]
However DNS server has been added to code now. If google DNS servers are not reachable, it will look into cloudflare DNS servers.
Thank you

**Comment by engageub** [comment]
> It just keeps on retrying.

Could you please share screenshot of retry.

Thank you

**Comment by engageub** [comment]
Closing this since there is no issue with the script. Please feel free to reopen if the issue still persists.
Thank you
