### ISSUE TITLE
Honeygain not running with proxy

### ISSUE THREAD

**Issue by phuonganh2601** [engageub/InternetIncome#60]
Honeygain show log starting but not connected, on dashboard show Waiting for traffic...

```  $$\   $$\                                                             $$\           
  $$ |  $$ |                                                            \__|          
  $$ |  $$ | $$$$$$\  $$$$$$$\   $$$$$$\  $$\   $$\  $$$$$$\   $$$$$$\  $$\ $$$$$$$\  
  $$$$$$$$ |$$  __$$\ $$  __$$\ $$  __$$\ $$ |  $$ |$$  __$$\  \____$$\ $$ |$$  __$$\ 
  $$  __$$ |$$ /  $$ |$$ |  $$ |$$$$$$$$ |$$ |  $$ |$$ /  $$ | $$$$$$$ |$$ |$$ |  $$ |
  $$ |  $$ |$$ |  $$ |$$ |  $$ |$$   ____|$$ |  $$ |$$ |  $$ |$$  __$$ |$$ |$$ |  $$ |
  $$ |  $$ |\$$$$$$  |$$ |  $$ |\$$$$$$$\ \$$$$$$$ |\$$$$$$$ |\$$$$$$$ |$$ |$$ |  $$ |
  \__|  \__| \______/ \__|  \__| \_______| \____$$ | \____$$ | \_______|\__|\__|  \__|
                                          $$\   $$ |$$\   $$ |                        
                                          \$$$$$$  |\$$$$$$  |                        
                                           \______/  \______/                         
TOU are accepted
Authorisation successful
ID: ...
Honeygain service is starting
```
I tested tun2socks and proxy, it working fine. But only honeygain not working. Hang on "Honeygain service is starting"

**Comment by engageub** [comment]
Hi,
Honeygain usually shows waiting for traffic and it may take upto an hour to receive traffic. 
If you are using residential IPs which are whitelisted by honeygain, the traffic is immediate(within 30 minutes).
Could you please let me know how long has it been since you started the honeygain containers.
Other users are using it without any issues. Please make sure you are using the latest version of InternetIncome Script from github.  Also ensure that you have enough resources on your system (cpu,memory,diskspace etc). 

Thank you

**Comment by engageub** [comment]
Could you please confirm the architecture you are using with honeygain. Arm64 or amd64?
Thank you

**Comment by phuonganh2601** [comment]
I'm using VPS Oracle 4 core 24GB RAM and architecture  ARM64.
I'm installed this docker container to run AMD64.
```docker run --privileged --rm tonistiigi/binfmt --install all```
I will try again and wait 30 minutes.

**Comment by phuonganh2601** [comment]
Docker show that
```
  $$\   $$\                                                             $$\           
  $$ |  $$ |                                                            \__|          
  $$ |  $$ | $$$$$$\  $$$$$$$\   $$$$$$\  $$\   $$\  $$$$$$\   $$$$$$\  $$\ $$$$$$$\  
  $$$$$$$$ |$$  __$$\ $$  __$$\ $$  __$$\ $$ |  $$ |$$  __$$\  \____$$\ $$ |$$  __$$\ 
  $$  __$$ |$$ /  $$ |$$ |  $$ |$$$$$$$$ |$$ |  $$ |$$ /  $$ | $$$$$$$ |$$ |$$ |  $$ |
  $$ |  $$ |$$ |  $$ |$$ |  $$ |$$   ____|$$ |  $$ |$$ |  $$ |$$  __$$ |$$ |$$ |  $$ |
  $$ |  $$ |\$$$$$$  |$$ |  $$ |\$$$$$$$\ \$$$$$$$ |\$$$$$$$ |\$$$$$$$ |$$ |$$ |  $$ |
  \__|  \__| \______/ \__|  \__| \_______| \____$$ | \____$$ | \_______|\__|\__|  \__|
                                          $$\   $$ |$$\   $$ |                        
                                          \$$$$$$  |\$$$$$$  |                        
                                           \______/  \______/                         
TOU are accepted
Authorisation successful
ID: ...
Honeygain service is starting
API Ping Error: api call: http request error: Post "https://api.honeygain.com/api/v1/ping": read tcp 198.18.0.1:41052->104.26.13.49:443: read: connection reset by peer

```

**Comment by engageub** [comment]
Could you please let me know if you are using socks5 proxy or http proxy?
Could you also look into tun2socks logs to see if something is not supported on your proxy.

Thank you

**Comment by engageub** [comment]
The ip mentioned above is cloudflare IP address. It may have blacklisted your IP address or there is something missing.
Can you try to access the following URL manually using your browser through the same IP address you were using .
https://api.honeygain.com/api/v1/ping

Thank you

**Comment by phuonganh2601** [comment]
I'm using socks5 proxy (HTTP Proxy not working).
Socks5 format
```
socks5://user:pass@ip:port
```
Here is tun2socks logs.
```
time="2023-10-13T07:02:42Z" level=info msg="[TCP] 198.18.0.1:57410 <-> 104.16.249.249:443"
time="2023-10-13T07:02:52Z" level=info msg="[TCP] 198.18.0.1:52418 <-> 104.26.13.49:443"
time="2023-10-13T07:03:43Z" level=info msg="[TCP] 198.18.0.1:51254 <-> 104.16.249.249:443"
time="2023-10-13T07:03:43Z" level=info msg="[TCP] 198.18.0.1:51240 <-> 104.16.249.249:443"
time="2023-10-13T07:03:52Z" level=info msg="[TCP] 198.18.0.1:37588 <-> 104.26.13.49:443"
time="2023-10-13T07:04:43Z" level=info msg="[TCP] 198.18.0.1:52042 <-> 104.16.248.249:443"
time="2023-10-13T07:04:43Z" level=info msg="[TCP] 198.18.0.1:56330 <-> 104.16.249.249:443"
time="2023-10-13T07:04:52Z" level=info msg="[TCP] 198.18.0.1:39922 <-> 104.26.13.49:443"
time="2023-10-13T07:05:44Z" level=info msg="[TCP] 198.18.0.1:44802 <-> 104.16.249.249:443"
time="2023-10-13T07:05:44Z" level=info msg="[TCP] 198.18.0.1:44800 <-> 104.16.249.249:443"
time="2023-10-13T07:05:56Z" level=warning msg="[TCP] dial 104.26.13.49:443: connect to x.x.x.x:9502: dial tcp: lookup x.x.x.x: i/o timeout"
time="2023-10-13T07:06:45Z" level=info msg="[TCP] 198.18.0.1:41168 <-> 104.16.248.249:443"
time="2023-10-13T07:06:45Z" level=info msg="[TCP] 198.18.0.1:44206 <-> 104.16.249.249:443"
time="2023-10-13T07:06:47Z" level=info msg="[TCP] 198.18.0.1:34396 <-> 104.26.13.49:443"
```

**Comment by engageub** [comment]
It shows timeout. The DNS server resolves to 3 IP address of cloudflare. One of them may be causing issue. 
You may have to stop and restart to see if it picks up another server or add the DNS names manually in /etc/hosts file to redirect to another IP address. 

https://www.nslookup.io/domains/api.honeygain.com/dns-records/

Thank you

**Comment by engageub** [comment]
Honeygain may also be overloaded. It may keep retrying to connect. Please wait for an hour and see if you receive any traffic.
Thank you

**Comment by phuonganh2601** [comment]
I try socks5 + honeygain (without tun2socks) on local device and it working normal.
So I think problem with tun2socks.
Thank you!

```
  $$\   $$\                                                             $$\           
  $$ |  $$ |                                                            \__|          
  $$ |  $$ | $$$$$$\  $$$$$$$\   $$$$$$\  $$\   $$\  $$$$$$\   $$$$$$\  $$\ $$$$$$$\  
  $$$$$$$$ |$$  __$$\ $$  __$$\ $$  __$$\ $$ |  $$ |$$  __$$\  \____$$\ $$ |$$  __$$\ 
  $$  __$$ |$$ /  $$ |$$ |  $$ |$$$$$$$$ |$$ |  $$ |$$ /  $$ | $$$$$$$ |$$ |$$ |  $$ |
  $$ |  $$ |$$ |  $$ |$$ |  $$ |$$   ____|$$ |  $$ |$$ |  $$ |$$  __$$ |$$ |$$ |  $$ |
  $$ |  $$ |\$$$$$$  |$$ |  $$ |\$$$$$$$\ \$$$$$$$ |\$$$$$$$ |\$$$$$$$ |$$ |$$ |  $$ |
  \__|  \__| \______/ \__|  \__| \_______| \____$$ | \____$$ | \_______|\__|\__|  \__|
                                          $$\   $$ |$$\   $$ |                        
                                          \$$$$$$  |\$$$$$$  |                        
                                           \______/  \______/                         
TOU are accepted
Authorisation successful
ID: .......
Honeygain service is starting
Honeygain service is connected and running
```

**Comment by copystring** [comment]
I have this issue as well. All other services work fine, but honeygain does not work via proxy for two weeks.

**Comment by engageub** [comment]
Hi,
Honeygain docker has been updated 5 days back.
Could you please delete and start the containers if not already. 


Thank you

**Comment by copystring** [comment]
Oh, okay. I enabled DNS through socks5 proxy. It seems to work again. Thank you for the easy fix.

**Comment by copystring** [comment]
Actually, no. I checked again and made a mistake in my setup. I'm afraid it still does not work even with the latest honeygain container and test branch. Direct connection always works. Proxy connection does not. Proxies are socks5 with DNS via proxy enabled. DNS via proxy disabled also does not work.

All the honeygain docker containers have the same log:

```
TOU are accepted
Authorisation successful
ID: 4a50f2a71ee606ac95c66e44caa1c7bb20b6524ff058fd7a94e22f18bd1c4c11
Honeygain service is starting
API Ping Error: api call: http request error: Post "https://api.honeygain.com/api/v1/ping": context deadline exceeded
API Ping Error: api call: http request error: Post "https://api.honeygain.com/api/v1/ping": context deadline exceeded
```

Is the tunproxy branch different/better?

**Comment by copystring** [comment]
Any idea what I can do? Seems like an issue with tun2socks

**Comment by engageub** [comment]
Hi,
Honeygain has made changes and updated to latest version. Are you not using the latest version.
Are you using socks5 DNS or direct dns.

Thank you

**Comment by engageub** [comment]
Can you try tunproxy branch for honeygain and see if there is any difference.

https://github.com/engageub/InternetIncome/tree/tunproxy


Thank you

**Comment by copystring** [comment]
I'm using 0.8.1 of honeygain with socks5 DNS. Direct DNS did also not work.

I switch to tunproxy branch but tunproxy branch does not support EBESUCHER_USE_CHROME and ADNADE_USE_CHROME?

**Comment by engageub** [comment]
> I'm using 0.8.1 of honeygain with socks5 DNS. Direct DNS did also not work.
> 
> I switch to tunproxy branch but tunproxy branch does not support EBESUCHER_USE_CHROME and ADNADE_USE_CHROME?

Yes, it does not support. Its a clone of main branch but uses tun2proxy instead of tun2socks. Use it only for honeygain and let me know if its working fine.

**Comment by copystring** [comment]
I tried tunproxy branch with direct dns and socks dns. Both don't work.

```
TOU are accepted
Authorisation successful
ID: XXXXXXX
Honeygain service is starting
API Ping Error: api call: http request error: Post "https://api.honeygain.com/api/v1/ping": read tcp 198.18.0.1:48604->104.26.13.49:443: read: connection reset by peer
```

**Comment by engageub** [comment]
May be your proxy issue. 
There was another discussion regarding honeygain where its mentioned that older version of honeygain was working.
Please see the discussion below. 
User has changed to older version honeygain/honeygain:0.6.6 and it was confirmed to be working. 

https://github.com/engageub/InternetIncome/discussions/71


Thank you

**Comment by engageub** [comment]
Is the older version working with your proxy?

Thank you

**Comment by copystring** [comment]
Yes, looks good. 0.6.6 Works fine. Thank you!
