### ISSUE TITLE
Repocket error after work 1 day 

### ISSUE THREAD

**Issue by hoanguyenHy** [engageub/InternetIncome#72]
MainSocket -> before re connect 66.42.58.145
main socket re connected
MainSocket -> close false
doneHandler false

**Comment by engageub** [comment]
Hi,
May I know if you are using proxy or direct connection?
Could you please check your cpu and memory utilization.
For any issues related to containers, you have to check with repocket support team.
Official docker image for repocket is being used.

Thank you

**Comment by engageub** [comment]
In addition to this, could you please check your repocket dashboard also if the devices are online or offline.
If you are using proxy, could you please check tun2socks logs to see if there are any issues with connectivity.

Thank you

**Comment by engageub** [comment]
Closing this one as there is no further response.
The script integrates multiple docker containers. Docker images are not owned by me.
If you find any issue, please share respective logs as mentioned above.
