### ISSUE TITLE
Ebesucher surfbar used multiple times

### ISSUE THREAD

**Issue by ppzzAn** [engageub/InternetIncome#74]
Hi

Ebesucher fail for some reason only 10 Ip opened 
![Screenshot_23](https://github.com/engageub/InternetIncome/assets/129802150/9dc92978-45bf-42b6-81fd-85b80c5bc303)

**Comment by engageub** [comment]
Hello,
Could you please confirm if you are using main branch or test branch. 
May be it needs delay of 5 minutes similar to adnade script.

Thank you

**Comment by engageub** [comment]
Hi,
Could you please use the test branch and confirm if its working fine.
```
https://github.com/engageub/InternetIncome/tree/test
```

Also could you please if you are using shared proxy or dedicated proxy?
If you are using shared proxy or public proxy it may not work. 

Thank you

**Comment by ppzzAn** [comment]
> Hello, Could you please confirm if you are using main branch or test branch. May be it needs delay of 5 minutes similar to adnade script.
> 
> Thank you

Hi

Test branch.

Will test and reply.

**Comment by engageub** [comment]
Recently changes have been made for firefox profilein test branch by only keeping what is required. This will create new files for firefox profile each time  before it is started. 
However main branch is not affected by this. 

Thank you

**Comment by ppzzAn** [comment]
> Recently changes have been made for firefox profile in test branch by only keeping what is required. This will create new files for firefox profile each time before it is started. However main branch is not affected by this.
> 
> Thank you

At the minute works fine, that message gone 

Thank you

**Comment by engageub** [comment]
okay. I am closing this one. Let me know if it appears after 2 hours as it restarts after 2 hours in test branch from now on.

Thank you

**Comment by ppzzAn** [comment]
> okay. I am closing this one. Let me know if it appears after 2 hours as it restarts after 2 hours in test branch from now on.
> 
> Thank you

Same message 
![Screenshot_26](https://github.com/engageub/InternetIncome/assets/129802150/6b52f3d8-67ca-4c81-a2d2-781d64df6eed)

**Comment by engageub** [comment]
Did it happen after 2 hours?
Can you try main branch. Also please see that each
 browser  has unique ip address.

 Thank  you

**Comment by ppzzAn** [comment]
It happen after it passed captcha service.
For 9 browsers from 10 stays this message.

**Comment by engageub** [comment]
If this happens in main branch, then ebesucher has
changed something recently.

Thank you

**Comment by engageub** [comment]
Thank you.
Are you saying that the problem starts after 9 browsers?
Does it happen the same in main branch also.
Have you checked that proxies are unique.

Thank you

**Comment by ppzzAn** [comment]
> Thank you. Are you saying that the problem starts after 9 browsers? Does it happen the same in main branch also. Have you checked that proxies are unique. Thank you

Yes 1 browser surfing all rest stays with this message.
Proxy Unique
Didn't test a main branch

**Comment by engageub** [comment]
If you confirm main branch is working fine. I will revert changes in
firefox in test branch.

**Comment by ppzzAn** [comment]
> If you confirm main branch is working fine. I will revert changes in firefox in test branch. 

On main branch is same issue

**Comment by engageub** [comment]
Thank you. In that case ebesucher has made some changes or you are using IP's from same subnet.
Let me buy few residential proxies now and see if there is issue here.
You can try chrome from test branch in the mean time. 

Thank you

**Comment by ppzzAn** [comment]
> Thank you. In that case ebesucher has made some changes or you are using IP's from same subnet. Let me buy few residential proxies now and see if there is issue here. You can try chrome from test branch in the mean time.
> 
> Thank you

I have few Ip from same subnets, maybe there is an issue

**Comment by engageub** [comment]
Can you use IP's from different subnets. It shows it is using same display device. So it may be something related with respect to resolution or display of the device also.

**Comment by engageub** [comment]
Also, can you try chrome by changing the value for EBESUCHER_USE_CHROME to true for ebesucher.

**Comment by ppzzAn** [comment]
> Also, can you try chrome by changing the value for EBESUCHER_USE_CHROME to true for ebesucher.

I'm testing that now

**Comment by engageub** [comment]
Hello,
It a different issue. But I ran it now with 2 proxies and it works fine without any issue.

Thank you

**Comment by engageub** [comment]
Tested with 3 proxies and is working fine.

**Comment by engageub** [comment]
In addition to the above, I would like to know if you are accessing the browsers using serveo.net or directly using 127.0.0.1 urls.
I will give you 10 proxies to you if you would like to test. I don't see any issues here. 

Thank you

**Comment by ppzzAn** [comment]
I run more proxies maybe that's why it happened. I added a parameter to change firefox width and height. See how it will go

**Comment by engageub** [comment]
Yes, you can add random width and height using the following and passing them to docker. 

WINDOW_WIDTH=$((RANDOM % 1920 + 800))
WINDOW_HEIGHT=$((RANDOM % 1080 + 600))


Thank you

**Comment by engageub** [comment]
You may use the following code. Replace the older docker parameters with the following.

```
   WINDOW_WIDTH=$((RANDOM % 1920 + 800))
    WINDOW_HEIGHT=$((RANDOM % 1080 + 600))
    echo $WINDOW_WIDTH $WINDOW_HEIGHT

    docker_parameters=($LOGS_PARAM $MAX_MEMORY_PARAM $MEMORY_RESERVATION_PARAM $CPU_PARAM $NETWORK_TUN -e FF_OPEN_URL="https://www.ebesucher.com/surfbar/$EBESUCHER_USERNAME" -e WINDOW_WIDTH=$WINDOW_WIDTH  -e WINDOW_HEIGHT=$WINDOW_HEIGHT -e VNC_LISTENING_PORT=-1 -v $PWD/$firefox_data_folder/data$i:/config:rw $eb_port jlesage/firefox)

```

**Comment by engageub** [comment]
If those don't work. You can use the following proxies and confirm if the error has gone.
May be your proxy issue.

10 Proxies: https://pastebin.com/40YhaGih
Password: ebBFLBekzn



Thank you

**Comment by engageub** [comment]
Hi,
Could you please update on this.
Does changing width and height of the display make any difference.
Did you also try the `10 proxies mentioned. 

Thank you

**Comment by engageub** [comment]
> You may use the following code. Replace the older docker parameters with the following.
> 
> ```
>    WINDOW_WIDTH=$((RANDOM % 1920 + 800))
>     WINDOW_HEIGHT=$((RANDOM % 1080 + 600))
>     echo $WINDOW_WIDTH $WINDOW_HEIGHT
> 
>     docker_parameters=($LOGS_PARAM $MAX_MEMORY_PARAM $MEMORY_RESERVATION_PARAM $CPU_PARAM $NETWORK_TUN -e FF_OPEN_URL="https://www.ebesucher.com/surfbar/$EBESUCHER_USERNAME" -e DISPLAY_WIDTH=$WINDOW_WIDTH  -e DISPLAY_HEIGHT=$WINDOW_HEIGHT -e VNC_LISTENING_PORT=-1 -v $PWD/$firefox_data_folder/data$i:/config:rw $eb_port jlesage/firefox)
> ```

The above command has been updated and containers have different width and height.

**Comment by engageub** [comment]
Test branch has been set to display random width and height for ebesucher firefox.

https://github.com/engageub/InternetIncome/tree/test

Thank you
