### ISSUE TITLE
bitping

### ISSUE THREAD

**Issue by skyecraft92** [engageub/InternetIncome#78]
after running bitping it, checking the dashboard shows it needs an update, so i tried changing the code with the updated docker code and it failed, so can you please look into it

**Comment by engageub** [comment]
Hi,
Changes are pushed to test branch for bitping as they have updated to newer version. It will be pushed to main branch soon.

https://github.com/engageub/InternetIncome/tree/test


Thank you

**Comment by skyecraft92** [comment]
thanks, as i have a few running nodes already, so what do i need to update

**Comment by engageub** [comment]
You have to use --delete option to delete and download the code again after the update.
You can use the test branch right away if you wish to use.
However, please wait for sometime, it is being updated for main branch.


Thank you

**Comment by engageub** [comment]
Changes have been pushed to main branch. Closing this.
