### ISSUE TITLE
[Feature Request] Earnapp and proxyrack data backup

### ISSUE THREAD

**Issue by SkullFace141** [engageub/InternetIncome#8]
Earnapp and proxyrack data backup

please implement data folder that can be backed up for EarnAPP and ProxyRack, like the MYST nodes folders.

Thanks

**Comment by engageub** [comment]
For earnapp, data is stored in the current folder in the recent update. But it will be deleted as soon as you use delete function in the script. This can be avoided similar to mysterium app.
Will need to see if it uses the folder again after deploying new container or overrides it.
Proxyrack did not provide custom volumes to store the data. The data is stored in  /app path in the docker container.
If it uses the same id again it will work else you will need to raise request to proxy rack team to update their docker image  to support custom volumes and use the data from custom volume. 
This request/issue  will be updated again after further analysis. 

Thank you

**Comment by engageub** [comment]
For earnapp UUID is required to identify and other data is not required to be added to dashboard automatically. The code has been pushed for earnapp already. 

Thank you

**Comment by engageub** [comment]
For proxyrack the volumes are not supported in official version. You may raise a request to proxyrack support team to add volumes in order to take backup. Please note that a new device is added to proxyrack automatically when you delete and start the container and if you delete the device from your dashboard , the amount earned for that device will also be removed from your account.  


Thank you

**Comment by SkullFace141** [comment]
did you test the EarnAPP backup and restore?

**Comment by engageub** [comment]
Please update the logs if you face any issue. 
Thank you

**Comment by engageub** [comment]
Changes have been pushed to test branch for earnapp,proxyrack and traffmonetizer

https://github.com/engageub/InternetIncome/tree/test

Thank you

**Comment by engageub** [comment]
Closing this since the backups are available now in test branch. You may download and confirm if there are any issues.

**Comment by SkullFace141** [comment]
Main branch EarnAPP backup is working

**Comment by SkullFace141** [comment]
> Changes have been pushed to test branch for earnapp,proxyrack and traffmonetizer
> 
> https://github.com/engageub/InternetIncome/tree/test
> 
> Thank you

what new changes did you do?

**Comment by engageub** [comment]
The changes for backup of earnapp,proxyrack and traffmonetizer.

Thank you

**Comment by SkullFace141** [comment]
where is Proxyrack node backup?

**Comment by engageub** [comment]
Its present in proxyrackdata folder. Is it not visible?  Then you might be using older version

Thank you

**Comment by engageub** [comment]
Would you mind responding to my queries on https://github.com/engageub/InternetIncome/issues/9 rather than only asking. This is not master slave relation.

Thank you
