### ISSUE TITLE
Honey Gain is not working for me

### ISSUE THREAD

**Issue by SkullFace141** [engageub/InternetIncome#84]
Honey Gain is not working for me
![image](https://github.com/engageub/InternetIncome/assets/122306481/1fe888f2-9428-46b8-963c-41f84959fd7c)

log

  $$\   $$\                                                             $$\
  $$ |  $$ |                                                            \__|
  $$ |  $$ | $$$$$$\  $$$$$$$\   $$$$$$\  $$\   $$\  $$$$$$\   $$$$$$\  $$\ $$$$$$$\
  $$$$$$$$ |$$  __$$\ $$  __$$\ $$  __$$\ $$ |  $$ |$$  __$$\  \____$$\ $$ |$$  __$$\
  $$  __$$ |$$ /  $$ |$$ |  $$ |$$$$$$$$ |$$ |  $$ |$$ /  $$ | $$$$$$$ |$$ |$$ |  $$ |
  $$ |  $$ |$$ |  $$ |$$ |  $$ |$$   ____|$$ |  $$ |$$ |  $$ |$$  __$$ |$$ |$$ |  $$ |
  $$ |  $$ |\$$$$$$  |$$ |  $$ |\$$$$$$$\ \$$$$$$$ |\$$$$$$$ |\$$$$$$$ |$$ |$$ |  $$ |
  \__|  \__| \______/ \__|  \__| \_______| \____$$ | \____$$ | \_______|\__|\__|  \__|
                                          $$\   $$ |$$\   $$ |
                                          \$$$$$$  |\$$$$$$  |
                                           \______/  \______/

TOU are accepted
Authorisation successful
ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Honeygain service is starting

**Comment by engageub** [comment]
Hello,
This happens even with direct connection on newer versions. It sometimes took a day get traffic.
Users have confirmed that older version of honeygain is working good with proxies.

Please change  honeygain/honeygain to  honeygain/honeygain:0.6.6 in internetIncome.sh file.

Reference: https://github.com/engageub/InternetIncome/discussions/71


Thank you

**Comment by engageub** [comment]
The script only redirects traffic through proxies and official versions of honeygain is used.

Thank you
