### ISSUE TITLE
earnapp

### ISSUE THREAD

**Issue by revozmund** [engageub/InternetIncome#85]
i dont really know if im missing something but every time i start and stop the script a new link appears in the earnapp,txt.
i currently have 5 proxys and im using my residential ip aswell

**Comment by engageub** [comment]
Could you please confirm if you are using main branch or test branch.
Also are you deleting any backups before starting the script.
What is the OS that this is being run on.

Thank you

**Comment by revozmund** [comment]
i am currently using the test branch
im not deleting the backups im just using the sudo bash internetIncome.sh --start and sudo bash internetIncome.sh --delete commands.
this is running on the latest version of ubuntu server with docker

**Comment by engageub** [comment]
In test branch if you are using proxies, please set USE_DIRECT_CONNECTION=false

Thank you

**Comment by revozmund** [comment]
sorry i should mention i have tried that aswell

**Comment by engageub** [comment]
You will still see 6 urls in earnapp.txt. It will pick up the first 5 in the list.
You can delete the backups and start again to generate only 5 urls.
I am closing the issue now. 

Thank you
