### ISSUE TITLE
tun2socks not running on vps 

### ISSUE THREAD

**Issue by dream996388** [engageub/InternetIncome#89]
Thank you for your project, I learned a lot, but have some questions. I use the same project in both vm and vps. The vm can run normally, but the vps cannot. This is the log of tun2socks.

Tun2socks:
```
time="2024-01-14T03:56:43Z" level=info msg="[DIALER] set fwmark: 0x22b"
time="2024-01-14T03:56:43Z" level=info msg="[STACK] tun://tun0 <-> socks5://{ip}:{port}"
```

The proxy does not seem to be working. Do I need to make additional network settings or other settings in the environment?

thanks for your reply!

**Comment by engageub** [comment]
Hello,
If you see that message in the logs, the container has started.
If your socks5 supports UDP, please enable DNS in properties.conf file
If your VPS has older kernel version, tun2socks will not work without DNS support on socks5 proxy.
In that case, you will have to use tunproxy branch.

https://github.com/engageub/InternetIncome/tree/tunproxy


Thank you

**Comment by engageub** [comment]
Also, make sure DNS servers 1.1.1.1 and 1.0.0.1 are reachable from your VPS.

**Comment by engageub** [comment]
Closing this as the answers have been given. 
Please update if further information is required on this.
