### ISSUE TITLE
Containers cannot be linked to Docker

### ISSUE THREAD

**Issue by danghai255** [engageub/InternetIncome#90]
When I run the completion command , the system reports that the Container has been successfully created . But the Docker side shows blank . I do not use Proxies
I followed the instructions here : https://github.com/engageub/InternetIncome
Please show me how to fix it. Thanks so much !!!

![Capture](https://github.com/engageub/InternetIncome/assets/78672480/605adf6b-952f-4c24-a0de-650902199e47)

![Capture1](https://github.com/engageub/InternetIncome/assets/78672480/aa451f7a-bb29-45ad-85b6-3726e9ff88c2)

**Comment by engageub** [comment]
Hello,
The docker command shows that the containers are running. The script is working as expected.
Please see the respective app dashboard if the apps are running.
Anything related to GUI, you will have to check with docker support Team. https://forums.docker.com/ 
If you are using windows docker desktop and ubuntu VM it may not appear as both run in isolated environment.

Thank you

**Comment by engageub** [comment]
If Docker Desktop in Linux is not showing containers, there are several potential reasons for this issue. Here are some troubleshooting steps you can follow:

Check Docker Daemon Status:
Ensure that the Docker daemon is running. You can check the status using the following command:

```
sudo systemctl status docker
```
If the daemon is not running, start it with:

```
sudo systemctl start docker
```
Verify Docker Installation:
Confirm that Docker is installed correctly on your system. You can check the Docker version with:

```
docker --version
```
Ensure that there are no errors or warnings in the output.

Check Docker Images:
Confirm that your containers and images exist. You can list all containers with:
```
docker ps -a
```
And list all images with:

```
docker images
```
If you don't see your containers or images, they might not have been created or might have been removed.

Review Docker Desktop Settings:
Open Docker Desktop and check its settings. Ensure that resources (CPU, memory) are allocated appropriately and that there are no conflicting configurations.

Check System Resource Usage:
Insufficient system resources (CPU, memory) can lead to containers not starting or appearing in Docker Desktop. Check your system resource usage to ensure there is enough available.

Restart Docker Desktop:
Try restarting Docker Desktop to see if it resolves the issue. Sometimes, a simple restart can solve problems.

Check Docker Logs:
Examine Docker logs for any error messages or issues. You can view the Docker daemon logs using:

```
sudo journalctl -u docker
```
Look for any error messages that might indicate why containers are not starting.

Firewall/Antivirus:
Sometimes, firewall or antivirus settings can interfere with Docker. Ensure that the necessary ports are open and that Docker is allowed through any firewall.

Update Docker:
Ensure that you are using the latest version of Docker. You can update Docker by following the instructions on the Docker website.

Reinstall Docker Desktop:
If all else fails, you might consider uninstalling and reinstalling Docker Desktop.

If the issue persists after trying these steps,  please open an issue in docker forums https://forums.docker.com/

Closing this as script is working as expected and the apps are running fine to generate income.
The script is CLI version and anything related to script will be answered or supported.

Thank you
