### ISSUE TITLE
md5sum on Macosx Apple M1

### ISSUE THREAD

**Issue by daysus** [engageub/InternetIncome#92]
I am testing on macosx Apple M1, the md5sum command is not working, it should be md5.

change in internetIncome.sh
UNIQUE_ID="$(echo -n "$RANDOM" | md5sum | cut -c1-32)"

to 

if [[ "$OSTYPE" != "darwin "* ]]; then
    UNIQUE_ID="$(echo -n "$RANDOM" | md5sum | cut -c1-32)"
else
    UNIQUE_ID="$(echo -n "$RANDOM" | md5 | cut -c1-32)"
fi

I tried to upload request, but I don't have permissions.

**Comment by engageub** [comment]
Hi,
The code is compatible with linux versions mentioned. This has not been tested on Mac OS.
I would suggest you to replace, it with the following and let me know if its working fine on Mac OS. Then the changes will be pushed to main branch. The following command works fine with linux. 

```
UNIQUE_ID=`cat /dev/urandom | LC_ALL=C tr -dc 'a-f0-9' | dd bs=1 count=32 2>/dev/null`
```

Thank you

**Comment by engageub** [comment]
Changes are in main branch now.
Please download the main branch and test again on MacOS.

https://github.com/engageub/InternetIncome

Let me know if its working fine on MACOS. The documentation in readme file will be updated that it supports MACOS also. 


Thank you

**Comment by engageub** [comment]
The containers are working but some of the commands do not seem to be work as expected and they have minor impact on running of the script. As an example colours are not working and -e is printed at the beginning of each line. 
If you see the devices being active in the respective dashboard with proxies, then the containers are working fine.

Thank you

**Comment by engageub** [comment]
Closing this as the script is working as expected. Support for MacOS is not mentioned in the Readme file. However, you may continue using it as long as the script works fine.

Thank you
