### ISSUE TITLE
containernames.txt file does not exist

### ISSUE THREAD

**Issue by pascaltuf** [engageub/InternetIncome#94]
I'm using the test branch for the first time and on first launch it tells me:
containernames.txt file does not exist. Exiting..
Where is this file created from, doesn't the code create it automatically?
In the folder I only have the repository files, I don't have anything else.
I don't use VPN, proxy, and direct connection, and all money making apps are enabled

**Comment by engageub** [comment]
The code is open source. If you know how to script you will know the reason for it.
For test branch you will have to set USE_DIRECT_CONNECTION to true in properties.conf for direct connection.

Please share the console logs after running the commands. Did you see any errors. 
I don't see any reason why that log message will appear. Have you made any modifications in the code?

You can also test it here https://labs.play-with-docker.com/

Thank you

**Comment by pascaltuf** [comment]
This is all I get in the console, I haven't changed anything in the code.
Starting..
Waiting 30 seconds before generating device Ids
containernames.txt file does not exist. Exiting..

**Comment by engageub** [comment]
You will have to set USE_DIRECT_CONNECTION=true in properties.conf in test branch.

Thank you

**Comment by engageub** [comment]
Closing this as the script is working as expected. It will only work if you specify the network configurations in properties.conf file.
This is not similar to main branch. It has multiple network configurations.

Thank you
