### ISSUE TITLE
Problem with VPS Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by daysus** [engageub/InternetIncome#95]
I have changed from Debian to Ubuntu and the same thing happens with xjasonlyu/tun2socks:v2.5.2

VPS Features:
2 CPU
1 GB RAM
12 GB DISK

```
open: Is a directory
Cannot find device "tun0"
Cannot find device "tun0"
Cannot find device "tun0"
time="2024-01-21T17:23:21Z" level=info msg="[DIALER] set fwmark: 0x22b"
time="2024-01-21T17:23:21Z" level=fatal msg="[ENGINE] failed to start: create tun: is a directory"
```

Any suggestions?

**Comment by engageub** [comment]
Please raise an issue with tun2socks team regarding the issue https://github.com/xjasonlyu/tun2socks/

An alternative to this, is tunproxy branch for older kernel versions.

https://github.com/engageub/InternetIncome/tree/tunproxy

Thank you

**Comment by engageub** [comment]
The error "Cannot find device 'tun0'" can occur if the /dev/net/tun device file is not present. The /dev/net/tun file is a character special file that is used by applications to communicate with the kernel's TUN/TAP (network tunneling) driver.

If the TUN/TAP driver is not loaded or the /dev/net/tun file is missing, applications that rely on it (such as VPN software) won't be able to create the necessary network tunnel devices like "tun0."

To address this issue, you can try the following steps:

Load the TUN/TAP Module:
```
sudo modprobe tun
```
This command attempts to load the TUN/TAP kernel module. If the module is not present, you may need to install it. The specific package containing the TUN/TAP module can vary depending on your Linux distribution.

Check for the /dev/net/tun Device File:

```
ls -l /dev/net/tun
```
Verify that the /dev/net/tun device file exists and has the correct permissions. If it doesn't exist, it may indicate a problem with the TUN/TAP module or its installation.

Create /dev/net/tun if Missing:
```
sudo mknod /dev/net/tun c 10 200
```
This command creates the /dev/net/tun character special file with the correct major and minor numbers. Note that this step is usually not necessary if the TUN/TAP module is loaded properly.

Check Kernel Messages:
View the kernel log messages to see if there are any errors related to the TUN/TAP module or the creation of the /dev/net/tun device file.

```
dmesg | grep tun
```
If you encounter difficulties or receive error messages during these steps, it's essential to investigate the specific error messages for further troubleshooting. Additionally, ensure that your system is set up to support TUN/TAP devices, which may involve installing the necessary packages or kernel modules based on your Linux distribution.

**Comment by engageub** [comment]
Closing this as this is not an issue with the script. However, updating the status here after following the steps will benefit other users who may face similar issues. 

Thank you

**Comment by engageub** [comment]
Thank you for the response and update on this. So this has to be done by your VPS support team?
Is the script working fine now. 

Thank you
