### ISSUE TITLE
Repocket access denied

### ISSUE THREAD

**Issue by daysus** [engageub/InternetIncome#97]
Docker client: 

```
peer-client-version: 1.1.41
Your current version is : 1.1.33
e { error: { data: { message: 'Access denined.' }, status: 403 } }
```

**Comment by engageub** [comment]
Hello,
Official docker container is being used.
Make sure you are using correct key.
If there is any issue with container you have to check with repocket support team. 

Thank you

**Comment by engageub** [comment]
Your repocket API key is present in the following page

https://app.repocket.co/bandwidth-earnings

**Comment by engageub** [comment]
You might have used Repocket ID instead of Repocket API Key.

Thank you
